(function(){
'use strict';
const VER='Beta 0.325';
window._cgOpenInterestH=(()=>{try{const v=parseInt(localStorage.getItem('dvl_cgOpenInterestH')||'112',10);return v>=78&&v<=220?v:112;}catch(_){return 112;}})();
window._cgLongShortH=(()=>{try{const v=parseInt(localStorage.getItem('dvl_cgLongShortH')||'104',10);return v>=72&&v<=210?v:104;}catch(_){return 104;}})();
window._dvlCgOscHit=window._dvlCgOscHit||{};
const CG_CACHE={oi:{key:'',data:[],fetching:false,ts:0,src:'',err:''},ls:{key:'',data:[],fetching:false,ts:0,src:'',err:''}};

function q(s,r){return (r||document).querySelector(s);}function qa(s,r){return Array.from((r||document).querySelectorAll(s));}
function val(id,def){const e=q('#'+id);return e?e.value:def;}function checked(id,def){const e=q('#'+id);return e?!!e.checked:def;}
function setImp(el,st){if(!el)return;Object.keys(st).forEach(k=>el.style.setProperty(k,st[k],'important'));}
function fmtMoney(v){v=+v||0;const a=Math.abs(v);if(a>=1e12)return '$'+(v/1e12).toFixed(2)+'T';if(a>=1e9)return '$'+(v/1e9).toFixed(2)+'B';if(a>=1e6)return '$'+(v/1e6).toFixed(1)+'M';if(a>=1e3)return '$'+(v/1e3).toFixed(0)+'K';return '$'+v.toFixed(0);} 
function clamp(x,a,b){return Math.max(a,Math.min(b,x));}
function coin(){try{return String(S.sym||'BTCUSDT').replace(/USDT|USD|PERP|BUSD/gi,'')||'BTC';}catch(_){return 'BTC';}}
function symbol(){try{return String(S.sym||'BTCUSDT').toUpperCase();}catch(_){return 'BTCUSDT';}}
function tfToPeriod(forCG){let tf=(val('cgSharedPeriod','auto')||'auto').toLowerCase();if(tf==='auto')tf=String((window.S&&S.tf)||'5m').toLowerCase();const cg=['1m','3m','5m','15m','30m','1h','4h','6h','8h','12h','1d','1w'];const bn=['5m','15m','30m','1h','2h','4h','6h','12h','1d'];if(forCG&&cg.includes(tf))return tf;if(bn.includes(tf))return tf;if(tf==='2h'&&forCG)return '1h';return '5m';}
function cgKey(){return (val('cgApiKey','')||'').trim();}
function sourcePref(){return val('cgDataSource','auto')||'auto';}
function shouldUseCG(){const s=sourcePref();return s==='coinglass'||(s==='auto'&&!!cgKey());}
function headers(){const h={'accept':'application/json'};if(cgKey())h['CG-API-KEY']=cgKey();return h;}
async function fetchJson(url,opts){const r=await fetch(url,Object.assign({cache:'no-store'},opts||{}));if(!r.ok)throw new Error('HTTP '+r.status);return await r.json();}
function arrFromResp(j){if(Array.isArray(j))return j; if(Array.isArray(j?.data))return j.data; if(Array.isArray(j?.data?.list))return j.data.list; if(Array.isArray(j?.data?.items))return j.data.items; if(Array.isArray(j?.result))return j.result; return [];}
function tsOf(o){if(Array.isArray(o))return +o[0]||+o.t||0;return +(o.timestamp||o.time||o.t||o.date||o.createTime||0);}
function nval(o,keys){if(Array.isArray(o)){for(const i of keys){const v=+o[i];if(Number.isFinite(v))return v;}return 0;}for(const k of keys){const v=+o[k];if(Number.isFinite(v))return v;}return 0;}
function oiParse(arr,isCg){return arr.map((o,idx)=>{const t=tsOf(o);let open=nval(o,['open','o',1]);let high=nval(o,['high','h',2]);let low=nval(o,['low','l',3]);let close=nval(o,['close','c','value','sumOpenInterestValue',4]);if(!isCg){close=nval(o,['sumOpenInterestValue','value','close','c']);open=idx?0:close;high=close;low=close;}if(!open)open=idx&&arr[idx-1]?nval(arr[idx-1],isCg?['close','c','value',4]:['sumOpenInterestValue','value','close','c']):close;if(!high)high=Math.max(open,close);if(!low)low=Math.min(open,close);return{t,open,high,low,close};}).filter(d=>d.t&&d.close>0).sort((a,b)=>a.t-b.t);} 
function lsParse(arr){return arr.map(o=>{const t=tsOf(o);const ratio=nval(o,['longShortRatio','ratio','long_short_ratio','longShort',1]);let long=nval(o,['longAccount','longAccountRatio','longRatio','long',2]);let short=nval(o,['shortAccount','shortAccountRatio','shortRatio','short',3]);if(long>1)long/=100;if(short>1)short/=100;if(!long&&!short&&ratio>0){long=ratio/(1+ratio);short=1/(1+ratio);}return{t,ratio:ratio||((short>0)?long/short:0),long,short};}).filter(d=>d.t&&d.ratio>0).sort((a,b)=>a.t-b.t);} 
async function fetchOI(){const useCg=shouldUseCG();const per=tfToPeriod(useCg);const key=[useCg?'cg':'binance',coin(),symbol(),per,val('cgOiUnit','usd')].join('|');if(CG_CACHE.oi.key===key&&Date.now()-CG_CACHE.oi.ts<45000)return;if(CG_CACHE.oi.fetching)return;CG_CACHE.oi.fetching=true;CG_CACHE.oi.err='';try{let data,src;if(useCg){const u='https://open-api-v4.coinglass.com/api/futures/open-interest/aggregated-history?symbol='+encodeURIComponent(coin())+'&interval='+encodeURIComponent(per)+'&limit=500&unit='+encodeURIComponent(val('cgOiUnit','usd'));data=oiParse(arrFromResp(await fetchJson(u,{headers:headers()})),true);src='COINGLASS AGG';}else{const u='https://fapi.binance.com/futures/data/openInterestHist?symbol='+encodeURIComponent(symbol())+'&period='+encodeURIComponent(tfToPeriod(false))+'&limit=500';data=oiParse(arrFromResp(await fetchJson(u)),false);src='BINANCE';}CG_CACHE.oi={key,data,fetching:false,ts:Date.now(),src,err:''};}catch(e){CG_CACHE.oi.fetching=false;CG_CACHE.oi.err=String(e&&e.message||e);if(useCg&&sourcePref()==='auto'){try{const u='https://fapi.binance.com/futures/data/openInterestHist?symbol='+encodeURIComponent(symbol())+'&period='+encodeURIComponent(tfToPeriod(false))+'&limit=500';const data=oiParse(arrFromResp(await fetchJson(u)),false);CG_CACHE.oi={key:'binance-fallback|'+symbol()+'|'+tfToPeriod(false),data,fetching:false,ts:Date.now(),src:'BINANCE FALLBACK',err:''};}catch(_){}}}}
async function fetchLS(){const useCg=shouldUseCG();const per=tfToPeriod(useCg);const mode=val('cgLsMode','global');const key=[useCg?'cg':'binance',mode,symbol(),per,val('cgExchange','Binance')].join('|');if(CG_CACHE.ls.key===key&&Date.now()-CG_CACHE.ls.ts<45000)return;if(CG_CACHE.ls.fetching)return;CG_CACHE.ls.fetching=true;CG_CACHE.ls.err='';try{let data,src;if(useCg){const ep=mode==='top'?'top-long-short-account-ratio':'global-long-short-account-ratio';const u='https://open-api-v4.coinglass.com/api/futures/'+ep+'/history?exchange='+encodeURIComponent(val('cgExchange','Binance'))+'&symbol='+encodeURIComponent(symbol())+'&interval='+encodeURIComponent(per)+'&limit=500';data=lsParse(arrFromResp(await fetchJson(u,{headers:headers()})));src='COINGLASS '+(mode==='top'?'TOP':'GLOBAL');}else{const ep=mode==='top'?'topLongShortAccountRatio':'globalLongShortAccountRatio';const u='https://fapi.binance.com/futures/data/'+ep+'?symbol='+encodeURIComponent(symbol())+'&period='+encodeURIComponent(tfToPeriod(false))+'&limit=500';data=lsParse(arrFromResp(await fetchJson(u)));src='BINANCE '+(mode==='top'?'TOP':'GLOBAL');}CG_CACHE.ls={key,data,fetching:false,ts:Date.now(),src,err:''};}catch(e){CG_CACHE.ls.fetching=false;CG_CACHE.ls.err=String(e&&e.message||e);if(useCg&&sourcePref()==='auto'){try{const ep=mode==='top'?'topLongShortAccountRatio':'globalLongShortAccountRatio';const u='https://fapi.binance.com/futures/data/'+ep+'?symbol='+encodeURIComponent(symbol())+'&period='+encodeURIComponent(tfToPeriod(false))+'&limit=500';const data=lsParse(arrFromResp(await fetchJson(u)));CG_CACHE.ls={key:'binance-fallback|'+mode+'|'+symbol(),data,fetching:false,ts:Date.now(),src:'BINANCE FALLBACK',err:''};}catch(_){}}}}
function ensureData(){try{if(window.S&&S.inds&&S.inds.cgOpenInterest)fetchOI().then(()=>{try{drawSoon();}catch(_){}});if(window.S&&S.inds&&S.inds.cgLongShort)fetchLS().then(()=>{try{drawSoon();}catch(_){}});}catch(_){}}
function valueAt(data,t){if(!data||!data.length)return null;let lo=0,hi=data.length-1;if(t<=data[0].t)return data[0];if(t>=data[hi].t)return data[hi];while(lo<hi){const m=(lo+hi+1)>>1;if(data[m].t<=t)lo=m;else hi=m-1;}return data[lo];}
function drawEye(ctx,x,y,on){ctx.save();ctx.strokeStyle='rgba(120,145,180,.76)';ctx.fillStyle='rgba(120,145,180,.76)';ctx.lineWidth=1.1;if(on){ctx.beginPath();ctx.moveTo(x-5,y);ctx.bezierCurveTo(x-2,y-3.5,x+2,y-3.5,x+5,y);ctx.bezierCurveTo(x+2,y+3.5,x-2,y+3.5,x-5,y);ctx.closePath();ctx.stroke();ctx.beginPath();ctx.arc(x,y,1.6,0,Math.PI*2);ctx.fill();}else{ctx.beginPath();ctx.moveTo(x-5,y);ctx.bezierCurveTo(x-2,y-2.5,x+2,y-2.5,x+5,y);ctx.stroke();ctx.beginPath();ctx.moveTo(x-5,y+5);ctx.lineTo(x+5,y-5);ctx.stroke();}ctx.restore();}
function drawGear(ctx,x,y){ctx.save();ctx.strokeStyle='rgba(120,145,180,.82)';ctx.lineWidth=1.15;ctx.beginPath();ctx.arc(x,y,5,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.arc(x,y,1.6,0,Math.PI*2);ctx.stroke();for(let i=0;i<8;i++){const a=i*Math.PI/4;ctx.beginPath();ctx.moveTo(x+Math.cos(a)*6.2,y+Math.sin(a)*6.2);ctx.lineTo(x+Math.cos(a)*8.0,y+Math.sin(a)*8.0);ctx.stroke();}ctx.restore();}
function cgBase(ctx,L,title,right,kind,key,settingsKey){ctx.save();ctx.fillStyle='#05070b';ctx.fillRect(0,L.pTop,ctx.canvas.clientWidth||ctx.canvas.width,L.pBot-L.pTop);ctx.strokeStyle='rgba(23,32,45,.82)';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(0,L.pTop+.5);ctx.lineTo(ctx.canvas.clientWidth||ctx.canvas.width,L.pTop+.5);ctx.stroke();const eyeX=L.plotLeft+12,eyeY=L.pTop+L.hdrH/2;const hidden=!!window['__dvl_'+key+'_hidden'];drawEye(ctx,eyeX,eyeY,!hidden);if(!hidden){ctx.font='700 '+Math.round(10*(window._csf||1))+'px monospace';ctx.textAlign='left';ctx.textBaseline='middle';ctx.fillStyle='rgba(160,178,205,.94)';ctx.fillText(title,eyeX+16,eyeY);}ctx.font='700 '+Math.round(9*(window._csf||1))+'px monospace';ctx.textAlign='right';ctx.textBaseline='middle';ctx.fillStyle=kind==='bear'?'rgba(255,95,110,.94)':kind==='bull'?'rgba(0,220,190,.94)':'rgba(135,155,185,.92)';ctx.fillText(right||'',L.scaleLeft-8,eyeY);const gx=Math.min(L.scaleLeft-84,eyeX+16+(hidden?0:ctx.measureText(title).width)+18);drawGear(ctx,gx,eyeY);window._dvlCgOscHit[key]={eye:{x1:eyeX-22,y1:eyeY-22,x2:eyeX+22,y2:eyeY+22},gear:{x1:gx-22,y1:eyeY-22,x2:gx+22,y2:eyeY+22},settings:settingsKey};ctx.strokeStyle='rgba(23,32,45,.55)';ctx.lineWidth=.7;for(let n=1;n<=3;n++){const y=L.plotTop+(L.plotBottom-L.plotTop)*n/4;ctx.beginPath();ctx.moveTo(L.plotLeft,y);ctx.lineTo(L.plotRight,y);ctx.stroke();}ctx.fillStyle='#05070b';ctx.fillRect(L.scaleLeft,L.pTop,(ctx.canvas.clientWidth||ctx.canvas.width)-L.scaleLeft,L.pBot-L.pTop);ctx.strokeStyle='rgba(23,32,45,.88)';ctx.beginPath();ctx.moveTo(L.scaleLeft+.5,L.pTop);ctx.lineTo(L.scaleLeft+.5,L.pBot);ctx.stroke();ctx.restore();}
function layout(W,H,pTop,pBot){return _dvlOscLayout(W,H,pTop,pBot);}function yMap(L,v,min,max){if(max<=min)max=min+1;return L.plotBottom-(v-min)/(max-min)*(L.plotBottom-L.plotTop);}function panelOffsets(clarH,flowH,lsH){const GAP=typeof PANEL_GAP!=='undefined'?PANEL_GAP:4;return (clarH?clarH+GAP:0)+(flowH?flowH+GAP:0)+(lsH?lsH+GAP:0);} 
window.__drawCGOpenInterestPanel=function(ctx,W,H,V,sc,x,h,lsH,flowH,clarH){ensureData();const data=CG_CACHE.oi.data||[];const off=panelOffsets(clarH,flowH,lsH);const pBot=H-10-off,pTop=pBot-h,L=layout(W,H,pTop,pBot);if(L.plotRight<=L.plotLeft)return;const vals=[];for(let i=V.a;i<V.b;i++){const d=valueAt(data,S.candles[i]?.t||0);if(d)vals.push(d);}const last=vals[vals.length-1];const prev=vals.length>1?vals[vals.length-2]:last;const pct=last&&prev?((last.close-prev.close)/prev.close*100):0;const kind=pct>0?'bull':pct<0?'bear':'neutral';cgBase(ctx,L,'CG AGG OI',last?fmtMoney(last.close)+' '+(pct>=0?'+':'')+pct.toFixed(2)+'%':(CG_CACHE.oi.fetching?'LOADING':'NO DATA'),kind,'cgOi','cgOpenInterest');ctx.save();ctx.beginPath();ctx.rect(L.plotLeft,L.plotTop,L.plotRight-L.plotLeft,L.plotBottom-L.plotTop);ctx.clip();if(vals.length){const min=Math.min(...vals.map(v=>v.low||v.close)),max=Math.max(...vals.map(v=>v.high||v.close));const bw=Math.max(2,(CW(W)/Math.max(1,V.span))*0.48);for(let i=V.a;i<V.b;i++){const d=valueAt(data,S.candles[i]?.t||0);if(!d)continue;const xx=x(i);const yo=yMap(L,d.open,min,max),yc=yMap(L,d.close,min,max),yh=yMap(L,d.high,min,max),yl=yMap(L,d.low,min,max);const bull=d.close>=d.open;ctx.strokeStyle=bull?'rgba(0,220,170,.82)':'rgba(255,95,80,.82)';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(xx,yh);ctx.lineTo(xx,yl);ctx.stroke();ctx.fillStyle=bull?'rgba(0,210,165,.54)':'rgba(255,95,80,.54)';ctx.fillRect(xx-bw/2,Math.min(yo,yc),bw,Math.max(2,Math.abs(yc-yo)));ctx.strokeRect(xx-bw/2,Math.min(yo,yc),bw,Math.max(2,Math.abs(yc-yo)));}ctx.fillStyle='rgba(120,145,180,.78)';ctx.font='700 8px monospace';ctx.textAlign='left';ctx.fillText(CG_CACHE.oi.src||'',L.plotLeft+8,L.plotBottom-5);}ctx.restore();};
window.__drawCGLongShortPanel=function(ctx,W,H,V,sc,x,h,flowH,clarH){ensureData();const data=CG_CACHE.ls.data||[];const off=(clarH?clarH+(typeof PANEL_GAP!=='undefined'?PANEL_GAP:4):0)+(flowH?flowH+(typeof PANEL_GAP!=='undefined'?PANEL_GAP:4):0);const pBot=H-10-off,pTop=pBot-h,L=layout(W,H,pTop,pBot);if(L.plotRight<=L.plotLeft)return;const vals=[];for(let i=V.a;i<V.b;i++){const d=valueAt(data,S.candles[i]?.t||0);if(d)vals.push(d);}const last=vals[vals.length-1];const kind=last?(last.ratio>1.03?'bull':last.ratio<.97?'bear':'neutral'):'neutral';const text=last?('L/S '+last.ratio.toFixed(2)+' · L '+Math.round((last.long||0)*100)+'%'):(CG_CACHE.ls.fetching?'LOADING':'NO DATA');cgBase(ctx,L,'CG L/S ACCOUNTS',text,kind,'cgLs','cgLongShort');ctx.save();ctx.beginPath();ctx.rect(L.plotLeft,L.plotTop,L.plotRight-L.plotLeft,L.plotBottom-L.plotTop);ctx.clip();const min=.45,max=1.85,mid=yMap(L,1,min,max);ctx.strokeStyle='rgba(0,212,255,.32)';ctx.setLineDash([4,6]);ctx.beginPath();ctx.moveTo(L.plotLeft,mid);ctx.lineTo(L.plotRight,mid);ctx.stroke();ctx.setLineDash([]);if(vals.length){const bw=Math.max(1,(CW(W)/Math.max(1,V.span))*0.56);for(let i=V.a;i<V.b;i++){const d=valueAt(data,S.candles[i]?.t||0);if(!d)continue;const xx=x(i),yy=yMap(L,d.ratio,min,max);ctx.fillStyle=d.ratio>=1?'rgba(0,215,170,.42)':'rgba(255,95,80,.42)';ctx.fillRect(xx-bw/2,Math.min(mid,yy),bw,Math.max(1,Math.abs(yy-mid)));}ctx.beginPath();let st=false;for(let i=V.a;i<V.b;i++){const d=valueAt(data,S.candles[i]?.t||0);if(!d)continue;const xx=x(i),yy=yMap(L,d.ratio,min,max);if(!st){ctx.moveTo(xx,yy);st=true;}else ctx.lineTo(xx,yy);}ctx.strokeStyle='rgba(0,225,240,.92)';ctx.lineWidth=1.8;ctx.shadowColor='rgba(0,225,240,.28)';ctx.shadowBlur=4;if(st)ctx.stroke();ctx.shadowBlur=0;ctx.fillStyle='rgba(120,145,180,.78)';ctx.font='700 8px monospace';ctx.textAlign='left';ctx.fillText(CG_CACHE.ls.src||'',L.plotLeft+8,L.plotBottom-5);}ctx.restore();};
function injectCards(){if(!window.S||!S.inds)return;S.inds.cgOpenInterest=!!S.inds.cgOpenInterest;S.inds.cgLongShort=!!S.inds.cgLongShort;if(q('[data-card="cgOpenInterest"]'))return;const anchor=q('[data-card="hvnClarity"]')||q('[data-card="flowAccel"]')||q('.ind-card');if(!anchor)return;const wrap=anchor.parentNode;const html=`
<div class="ind-card dvl-icd dvl325-cg-card dvl328-cg-card" data-card="cgOpenInterest" data-dvl-cat="clareza">
  <div class="dvl-icd-head"><div class="dvl-icd-icon" style="--ic-bg:rgba(34,211,238,.12);--ic-cl:#22d3ee"><svg viewBox="0 0 18 18" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><path d="M3 13.5V5.8"/><path d="M3 5.8l3.2 2.5L9 4.5l3 5 3-3.2"/><path d="M15 6.3v7.2"/><rect x="2.2" y="11.2" width="2.2" height="3.2" rx=".6" fill="currentColor" opacity=".20"/><rect x="7.9" y="8" width="2.2" height="6.4" rx=".6" fill="currentColor" opacity=".20"/><rect x="13.6" y="9.8" width="2.2" height="4.6" rx=".6" fill="currentColor" opacity=".20"/></svg></div><div class="dvl-icd-info"><div class="dvl-icd-name name">CG Open Interest</div><div class="dvl-icd-meta"><span class="dvl-bdg dvl-bdg-nat">NATIVO</span><span class="dvl-bdg dvl-bdg-on">ATIVO</span></div></div><div class="dvl-icd-ctrl"><div class="row" data-ind="cgOpenInterest"><span class="switch"></span></div><button class="gear" data-settings="cgOpenInterest" title="Configurar CG OI">&#9881;</button><button class="dvl-star" data-star="cgOpenInterest" type="button">★</button></div></div>
  <div class="ind-settings" id="settings-cgOpenInterest">
    <div class="dvl325-cg-row"><span class="k">Fonte</span><select class="select" id="cgDataSource"><option value="auto" selected>Auto CG/Binance</option><option value="coinglass">CoinGlass API</option><option value="binance">Binance público</option></select></div>
    <div class="dvl325-cg-row"><span class="k">CG API Key</span><input class="input dvl325-cg-key" id="cgApiKey" type="password" placeholder="opcional"></div>
    <div class="dvl325-cg-row"><span class="k">Período</span><select class="select" id="cgSharedPeriod"><option value="auto" selected>Auto TF</option><option value="5m">5m</option><option value="15m">15m</option><option value="30m">30m</option><option value="1h">1h</option><option value="4h">4h</option><option value="1d">1D</option></select></div>
    <div class="dvl325-cg-row"><span class="k">Unidade OI</span><select class="select" id="cgOiUnit"><option value="usd" selected>USD</option><option value="coin">Coin</option></select></div>
    <div class="dvl325-cg-row"><span class="k">Altura</span><input class="num" id="cgOpenInterestHeight" type="number" min="78" max="220" value="112"></div>
    <div class="dvl325-cg-note">Com API key: CoinGlass aggregated OI. Sem key: fallback Binance OI do símbolo.</div>
  </div>
</div>
<div class="ind-card dvl-icd dvl325-cg-card dvl328-cg-card" data-card="cgLongShort" data-dvl-cat="clareza">
  <div class="dvl-icd-head"><div class="dvl-icd-icon" style="--ic-bg:rgba(45,212,191,.12);--ic-cl:#2dd4bf"><svg viewBox="0 0 18 18" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><path d="M3 5h8.5"/><path d="M9 2.8L11.5 5 9 7.2"/><path d="M15 13H6.5"/><path d="M9 10.8L6.5 13 9 15.2"/><path d="M4.3 9h9.4" stroke-opacity=".35"/></svg></div><div class="dvl-icd-info"><div class="dvl-icd-name name">CG Taker L/S</div><div class="dvl-icd-meta"><span class="dvl-bdg dvl-bdg-nat">NATIVO</span><span class="dvl-bdg dvl-bdg-on">ATIVO</span></div></div><div class="dvl-icd-ctrl"><div class="row" data-ind="cgLongShort"><span class="switch"></span></div><button class="gear" data-settings="cgLongShort" title="Configurar CG Long/Short">&#9881;</button><button class="dvl-star" data-star="cgLongShort" type="button">★</button></div></div>
  <div class="ind-settings" id="settings-cgLongShort">
    <div class="dvl325-cg-row"><span class="k">Fonte</span><select class="select" id="cgDataSourceMirror"><option value="same" selected>Usar fonte do OI</option></select></div>
    <div class="dvl325-cg-row"><span class="k">Exchange</span><select class="select" id="cgExchange"><option value="Binance" selected>Binance</option><option value="Bybit">Bybit</option><option value="OKX">OKX</option><option value="Bitget">Bitget</option></select></div>
    <div class="dvl325-cg-row"><span class="k">Accounts</span><select class="select" id="cgLsMode"><option value="accounts-global" selected>Accounts global</option><option value="accounts-top">Top accounts</option></select></div>
    <div class="dvl325-cg-row"><span class="k">Altura</span><input class="num" id="cgLongShortHeight" type="number" min="72" max="210" value="104"></div>
    <div class="dvl325-cg-note">Ratio acima de 1 = mais contas long. Abaixo de 1 = mais contas short.</div>
  </div>
</div>`;anchor.insertAdjacentHTML('afterend',html);bindInjected();}
function bindInjected(){qa('.row[data-ind="cgOpenInterest"],.row[data-ind="cgLongShort"]').forEach(r=>{if(r.dataset.dvl325Bound)return;r.dataset.dvl325Bound='1';r.onclick=function(ev){ev.stopPropagation();const k=r.dataset.ind;S.inds[k]=!S.inds[k];qa('[data-ind="'+k+'"]').forEach(n=>n.classList.toggle('on',!!S.inds[k]));ensureData();drawSoon&&drawSoon();};});qa('.gear[data-settings="cgOpenInterest"],.gear[data-settings="cgLongShort"]').forEach(g=>{if(g.dataset.dvl325Bound)return;g.dataset.dvl325Bound='1';g.onclick=function(ev){ev.stopPropagation();if(typeof window.openInputModal==='function')window.openInputModal(g.dataset.settings,g);};});['cgDataSource','cgApiKey','cgSharedPeriod','cgOiUnit','cgOpenInterestHeight','cgExchange','cgLsMode','cgLongShortHeight'].forEach(id=>{const el=q('#'+id);if(el&&!el.dataset.dvl325Bound){el.dataset.dvl325Bound='1';el.addEventListener('input',settingsChanged);el.addEventListener('change',settingsChanged);}});syncToggles();}
function settingsChanged(){window._cgOpenInterestH=clamp(parseInt(val('cgOpenInterestHeight',window._cgOpenInterestH)||window._cgOpenInterestH,10),78,220);window._cgLongShortH=clamp(parseInt(val('cgLongShortHeight',window._cgLongShortH)||window._cgLongShortH,10),72,210);try{localStorage.setItem('dvl_cgOpenInterestH',String(window._cgOpenInterestH));localStorage.setItem('dvl_cgLongShortH',String(window._cgLongShortH));}catch(_){}CG_CACHE.oi.key='';CG_CACHE.ls.key='';ensureData();try{drawSoon();}catch(_){}}
function syncToggles(){if(!window.S||!S.inds)return;qa('[data-ind="cgOpenInterest"]').forEach(n=>n.classList.toggle('on',!!S.inds.cgOpenInterest));qa('[data-ind="cgLongShort"]').forEach(n=>n.classList.toggle('on',!!S.inds.cgLongShort));}
function makeOverlays(){const wrap=q('#chartWrap');if(!wrap)return;['cgOi','cgLs'].forEach(k=>{['eye','gear'].forEach(t=>{const id='dvl325_'+k+'_'+t; if(q('#'+id))return;const b=document.createElement('button');b.id=id;b.className='dvl325-cg-'+t+'-overlay';b.type='button';b.addEventListener('click',function(ev){ev.preventDefault();ev.stopPropagation();const hit=window._dvlCgOscHit&&window._dvlCgOscHit[k];if(!hit)return;if(t==='eye'){window['__dvl_'+k+'_hidden']=!window['__dvl_'+k+'_hidden'];try{localStorage.setItem('dvl_'+k+'_hidden',window['__dvl_'+k+'_hidden']?'1':'');}catch(_){}drawSoon&&drawSoon();}else{const settings=hit.settings;const gear=q('.gear[data-settings="'+settings+'"]');if(typeof window.openInputModal==='function')window.openInputModal(settings,gear||null);}});wrap.appendChild(b);});});}
function updateOverlays(){makeOverlays();['cgOi','cgLs'].forEach(k=>{const hit=window._dvlCgOscHit&&window._dvlCgOscHit[k];const active=(k==='cgOi')?!!(S&&S.inds&&S.inds.cgOpenInterest&&S.candles&&S.candles.length):!!(S&&S.inds&&S.inds.cgLongShort&&S.candles&&S.candles.length);['eye','gear'].forEach(t=>{const b=q('#dvl325_'+k+'_'+t);if(!b)return;const box=hit&&hit[t];if(!active||!box){b.style.display='none';b.style.pointerEvents='none';return;}b.style.left=box.x1+'px';b.style.top=box.y1+'px';b.style.width=(box.x2-box.x1)+'px';b.style.height=(box.y2-box.y1)+'px';b.style.display='block';b.style.pointerEvents='auto';});});}
function hookDraw(){const old=window.draw;if(typeof old!=='function'||old.__dvl325Cg)return;const wrapped=function(){const r=old.apply(this,arguments);try{syncToggles();updateOverlays();}catch(_){}return r;};wrapped.__dvl325Cg=true;try{window.draw=wrapped;}catch(_){}}
function forceVersion(){try{window.DVL_APP_VERSION=VER;}catch(_){}qa('#dvlVersionBadge,.dvl-version-badge,.dvl-version-header,.dvl-version-logo-hidden,.beta-badge,.version-badge').forEach(b=>{if(b)b.textContent=VER;});try{window.DVL_CHANGELOG=window.DVL_CHANGELOG||[];const note='Added CoinGlass-style Aggregated Open Interest and Long/Short Ratio account oscillator panels with CoinGlass API support and Binance public fallback.';if(!window.DVL_CHANGELOG.some(x=>x&&x.version===VER&&x.note===note))window.DVL_CHANGELOG.unshift({version:VER,date:new Date().toISOString(),note});}catch(_){}}
function boot(){forceVersion();if(window.S&&S.inds){if(!('cgOpenInterest'in S.inds))S.inds.cgOpenInterest=false;if(!('cgLongShort'in S.inds))S.inds.cgLongShort=false;if(!S.oscScale)S.oscScale={};S.oscScale.cgOi=S.oscScale.cgOi||{center:0,range:200};S.oscScale.cgLs=S.oscScale.cgLs||{center:0,range:200};}injectCards();makeOverlays();hookDraw();ensureData();syncToggles();try{drawSoon&&drawSoon();}catch(_){}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();[180,500,1100,2200,4000].forEach(ms=>setTimeout(boot,ms));/* CG_CACHE ensureData interval removed — CG327 handles fetching */
})();