#!/usr/bin/env python3
"""Beta 0.117 — Strategy Tester: histórico real, gerador interno de sinais, Optimizer real"""

src = '/home/user/vick/DepthVisionLab-v106_REAL_UI/public/index.html'
with open(src, 'r', encoding='utf-8') as f:
    html = f.read()

# ── 1. version bump (IIFE only) ───────────────────────────────────────────────
OLD_V = "var V='Beta 0.116';"
NEW_V = "var V='Beta 0.117';"
assert OLD_V in html, 'IIFE version string not found'
html = html.replace(OLD_V, NEW_V, 1)

# ── 2. HTML version comment ───────────────────────────────────────────────────
OLD_CMT = '<!-- DVL_STRATEGY_TESTER v0.115 -->'
NEW_CMT = '<!-- DVL_STRATEGY_TESTER v0.117 -->'
assert OLD_CMT in html, 'DVL_STRATEGY_TESTER comment not found'
html = html.replace(OLD_CMT, NEW_CMT, 1)

# ── 3. engine comment ─────────────────────────────────────────────────────────
OLD_ENG = '/* ── deterministic backtest engine (Beta 0.116) ─────────────────── */'
NEW_ENG = '/* ── real backtest engine (Beta 0.117) ─────────────────────── */'
assert OLD_ENG in html, 'engine comment not found'
html = html.replace(OLD_ENG, NEW_ENG, 1)

# ── 4. changelog ──────────────────────────────────────────────────────────────
OLD_LOG = 'Beta 0.116\n  - Strategy Tester real-only:\n'
NEW_LOG = (
    'Beta 0.117\n'
    '  - Strategy Tester: hist\xf3rico real paginado da Binance\n'
    '    \xb7 _dvlFetchBTCandles: busca paginada at\xe9 10.000 candles com cache\n'
    '    \xb7 window.DVLBacktestData: cache de hist\xf3rico separado do gr\xe1fico\n'
    '    \xb7 _dvlGenHVNSigs: gerador puro de sinais HVN (sem dep. do DOM/chart)\n'
    '    \xb7 _backtestReal aceita candles/zonas pr\xe9-calculados (para optimizer)\n'
    '    \xb7 Badges: REAL HISTORY / CHART DATA / LIMITED HISTORY / NO HISTORY\n'
    '    \xb7 Backtest n\xe3o depende de window.S.hvnSignals plotados\n'
    '  - Optimizer real por combina\xe7\xe3o:\n'
    '    \xb7 Carrega hist\xf3rico real antes de otimizar\n'
    '    \xb7 Computa zonas HVN uma vez, reutiliza em todos os combos\n'
    '    \xb7 Cada combo gera seus pr\xf3prios sinais internamente\n'
    '    \xb7 FVG/TrendBreak: mensagem "em desenvolvimento"\n'
    '  - Sem mock: _backtest() retorna null se n\xe3o h\xe1 dados reais\n'
    'Beta 0.116\n'
    '  - Strategy Tester real-only:\n'
)
assert OLD_LOG in html, 'changelog anchor not found'
html = html.replace(OLD_LOG, NEW_LOG, 1)

# ── 5. add historical fetch infrastructure after var _btCache={} ──────────────
OLD_CACHE = 'var _btCache={};\n'
NEW_CACHE = (
    'var _btCache={};\n'
    '\n'
    '/* ── historical candle cache + backtest data store ── */\n'
    'var _dvlBTCache=new Map();\n'
    'window.DVLBacktestData={candles:[],symbol:"",timeframe:"",from:0,to:0,source:"none"};\n'
    '\n'
    'async function _dvlFetchBTCandles(sym,tf,periodDays,dateFrom,dateTo){\n'
    '  var now=Date.now();\n'
    '  var toMs=dateTo?new Date(dateTo).getTime()+86400000:now;\n'
    '  var fromMs=dateFrom?new Date(dateFrom).getTime():toMs-(Math.max(1,periodDays||30)*86400000);\n'
    '  var ckey=sym+\'|\'+tf+\'|\'+fromMs+\'|\'+toMs;\n'
    '  if(_dvlBTCache.has(ckey))return _dvlBTCache.get(ckey);\n'
    '  var candles=[],cursor=fromMs,maxC=10000;\n'
    '  while(cursor<toMs&&candles.length<maxC){\n'
    '    var url=\'https://api.binance.com/api/v3/klines?symbol=\'+sym+\'&interval=\'+tf+\n'
    '      \'&startTime=\'+cursor+\'&endTime=\'+toMs+\'&limit=1000\';\n'
    '    var r=await fetch(url);\n'
    '    if(!r.ok)throw new Error(\'Klines \'+r.status);\n'
    '    var batch=await r.json();\n'
    '    if(!Array.isArray(batch)||!batch.length)break;\n'
    '    batch.forEach(function(x){candles.push({t:+x[0],o:+x[1],h:+x[2],l:+x[3],c:+x[4],v:+x[5],delta:0,buy:0,sell:0,fp:new Map()});});\n'
    '    var lastT=+batch[batch.length-1][0];\n'
    '    if(batch.length<1000)break;\n'
    '    cursor=lastT+1;\n'
    '  }\n'
    '  _dvlBTCache.set(ckey,candles);\n'
    '  window.DVLBacktestData={candles:candles,symbol:sym,timeframe:tf,from:fromMs,to:toMs,source:\'fetched\'};\n'
    '  return candles;\n'
    '}\n'
)
assert OLD_CACHE in html, 'var _btCache anchor not found'
html = html.replace(OLD_CACHE, NEW_CACHE, 1)

# ── 6. add _dvlGenHVNSigs() after _isBothThresh ───────────────────────────────
OLD_THRESH = "function _isBothThresh(v){return typeof v==='string'&&v.indexOf('both')===0;}\n\n/* attempt real backtest"
NEW_THRESH = (
    "function _isBothThresh(v){return typeof v==='string'&&v.indexOf('both')===0;}\n"
    "\n"
    "/* Backtest must avoid lookahead bias.\n"
    "   HVN zones computed from historical candles — valid as zones are structural\n"
    "   price levels that accumulate over time and are visible in real-time. */\n"
    "function _dvlGenHVNSigs(candles,zones,cfg){\n"
    "  if(!candles||!candles.length||!zones||!zones.length)return[];\n"
    "  var n=candles.length;\n"
    "  var signals=new Array(n).fill(null);\n"
    "  var minW=(parseFloat(cfg.wickSens)||45)/100;\n"
    "  var sens=minW*0.4;\n"
    "  var cooldown=parseInt(cfg.cooldown||cfg.cons)||5;\n"
    "  var allowLat=(cfg.allowLat!==false);\n"
    "  var diveMin=parseInt(cfg.diveMin)||2;\n"
    "  var mode=cfg.mode||'wick';\n"
    "  var volSpike=cfg.volSpike||'off';\n"
    "  var minAtrHvn=parseFloat(cfg.minAtrHvn||cfg.hvnMinAtr)||0;\n"
    "  var doWick=(mode==='wick'||mode==='all');\n"
    "  var doDive=(mode==='dive'||mode==='all');\n"
    "  var doEngulf=(mode==='engulf'||mode==='all');\n"
    "  var _vA=new Float32Array(n);\n"
    "  if(volSpike&&volSpike!=='off'){\n"
    "    var _vs=0;\n"
    "    for(var vi=0;vi<n;vi++){_vA[vi]=vi>0?_vs/Math.min(vi,20):0;_vs+=(candles[vi].v||0);if(vi>=20)_vs-=(candles[vi-20].v||0);}\n"
    "  }\n"
    "  var _a14=new Float32Array(n);\n"
    "  if(minAtrHvn>0){\n"
    "    var _as=0;\n"
    "    for(var _ai=0;_ai<n;_ai++){\n"
    "      var _ca=candles[_ai],_pc=_ai>0?candles[_ai-1].c:_ca.o;\n"
    "      var _tr=Math.max(_ca.h-_ca.l,Math.abs(_ca.h-_pc),Math.abs(_ca.l-_pc));\n"
    "      _as+=_tr;\n"
    "      if(_ai>=14){var _oa=candles[_ai-14],_op=_ai>14?candles[_ai-15].c:_oa.o;\n"
    "        _as-=Math.max(_oa.h-_oa.l,Math.abs(_oa.h-_op),Math.abs(_oa.l-_op));}\n"
    "      _a14[_ai]=_as/Math.min(_ai+1,14);\n"
    "    }\n"
    "  }\n"
    "  for(var zi=0;zi<zones.length;zi++){\n"
    "    var z=zones[zi];var zSz=z.hi-z.lo;if(zSz<=0)continue;\n"
    "    var tol=zSz*sens,latCnt=0,lastSI=-999;\n"
    "    for(var i=0;i<n;i++){\n"
    "      var c=candles[i];\n"
    "      var bL=Math.min(c.o,c.c),bH=Math.max(c.o,c.c),cR=c.h-c.l;\n"
    "      if(cR<=0){latCnt=0;continue;}\n"
    "      if(bH>=z.lo&&bL<=z.hi){latCnt++;continue;}\n"
    "      var cOK=(i-lastSI>=cooldown);\n"
    "      var lOK=(allowLat||latCnt===0);\n"
    "      var vOK=(volSpike==='off'||!volSpike||_vA[i]<=0||(c.v||0)>=parseFloat(volSpike)*_vA[i]);\n"
    "      var aOK=(minAtrHvn<=0||cR>=minAtrHvn*_a14[i]);\n"
    "      if(doWick){\n"
    "        if(c.h>=z.lo&&c.c<z.lo+tol&&bL<z.lo){\n"
    "          var uW=c.h-Math.max(c.o,c.c),wP=uW/cR;\n"
    "          if(wP>=minW&&cOK&&lOK&&vOK&&aOK){if(!signals[i]||Math.abs(signals[i]._s||0)<wP){signals[i]={type:'short',kind:latCnt>=1?'lateral':'rejection',zone:z,wickPct:wP,_s:wP};lastSI=i;}}\n"
    "        }else if(c.l<=z.hi&&c.c>z.hi-tol&&bH>z.hi){\n"
    "          var lW=Math.min(c.o,c.c)-c.l,wP=lW/cR;\n"
    "          if(wP>=minW&&cOK&&lOK&&vOK&&aOK){if(!signals[i]||Math.abs(signals[i]._s||0)<wP){signals[i]={type:'long',kind:latCnt>=1?'lateral':'rejection',zone:z,wickPct:wP,_s:wP};lastSI=i;}}\n"
    "        }\n"
    "      }\n"
    "      if(doDive&&latCnt>=diveMin&&cOK&&vOK&&aOK){\n"
    "        if(bL>=z.hi&&c.c>c.o){var _d=(c.c-c.o)/(c.h-c.l||1);if(!signals[i]||signals[i]._s<_d){signals[i]={type:'long',subtype:'recover',zone:z,_s:_d};lastSI=i;}}\n"
    "        if(bH<=z.lo&&c.c<c.o){var _d=(c.o-c.c)/(c.h-c.l||1);if(!signals[i]||signals[i]._s<_d){signals[i]={type:'short',subtype:'recover',zone:z,_s:_d};lastSI=i;}}\n"
    "      }\n"
    "      if(doEngulf&&i>0&&cOK&&vOK&&aOK){\n"
    "        var _pv=candles[i-1],_pvL=Math.min(_pv.o,_pv.c),_pvH=Math.max(_pv.o,_pv.c);\n"
    "        if(_pvH>=z.lo&&_pvL<=z.hi){\n"
    "          if(c.c>c.o&&_pv.c<_pv.o&&c.o<=_pv.c&&c.c>=_pv.o){var _d=(c.c-c.o)/(_pvH-_pvL||1);if(!signals[i]||signals[i]._s<_d){signals[i]={type:'long',subtype:'engulf',zone:z,_s:_d};lastSI=i;}}\n"
    "          if(c.c<c.o&&_pv.c>_pv.o&&c.o>=_pv.c&&c.c<=_pv.o){var _d=(c.o-c.c)/(_pvH-_pvL||1);if(!signals[i]||signals[i]._s<_d){signals[i]={type:'short',subtype:'engulf',zone:z,_s:_d};lastSI=i;}}\n"
    "        }\n"
    "      }\n"
    "      latCnt=0;\n"
    "    }\n"
    "  }\n"
    "  var result=[];\n"
    "  for(var _si=0;_si<n;_si++){\n"
    "    var _sg=signals[_si];if(!_sg)continue;\n"
    "    var _sc=candles[_si];\n"
    "    _sg.side=_sg.type==='long'?'LONG':'SHORT';\n"
    "    _sg.timestamp=_sc.t;\n"
    "    _sg.entryPrice=_sc.c;\n"
    "    _sg.candle=_sc;\n"
    "    _sg.hvnZone=_sg.zone;\n"
    "    var _rt;\n"
    "    if(_sg.subtype==='recover'){_rt='Dive & Recover';}\n"
    "    else if(_sg.subtype==='engulf'){_rt='Engolfing';}\n"
    "    else if(_sg.kind==='lateral'){_rt=(_sg.type==='long')?'Lateral zone support rejection':'Lateral zone resistance rejection';}\n"
    "    else{_rt=(_sg.type==='long')?'Support rejection':'Resistance rejection';}\n"
    "    _sg.rejectionType=_rt;\n"
    "    _sg.id='sig_'+_sc.t+'_'+_sg.type.charAt(0);\n"
    "    _sg.idx=_si;\n"
    "    if(_sg.zone&&!_sg.zone.price)_sg.zone.price=(_sg.zone.lo+_sg.zone.hi)/2;\n"
    "    var _isL=(_sg.type==='long'),_nz=null,_nzD=Infinity;\n"
    "    for(var _zj=0;_zj<zones.length;_zj++){\n"
    "      var _z=zones[_zj];\n"
    "      if(_isL&&_z.lo>_sg.zone.hi){var _zd=_z.lo-_sg.zone.hi;if(_zd<_nzD){_nzD=_zd;_nz=_z;}}\n"
    "      else if(!_isL&&_z.hi<_sg.zone.lo){var _zd=_sg.zone.lo-_z.hi;if(_zd<_nzD){_nzD=_zd;_nz=_z;}}\n"
    "    }\n"
    "    _sg.nextHvnZone=_nz;\n"
    "    if(_nz&&!_nz.price)_nz.price=(_nz.lo+_nz.hi)/2;\n"
    "    result.push(_sg);\n"
    "  }\n"
    "  return result;\n"
    "}\n"
    "\n"
    "/* attempt real backtest"
)
assert OLD_THRESH in html, '_isBothThresh / attempt real backtest anchor not found'
html = html.replace(OLD_THRESH, NEW_THRESH, 1)

# ── 7. replace _backtestReal with version accepting precomputed candles+zones ──
OLD_BRT = (
    "/* attempt real backtest using actual candles + HVN signals if available */\n"
    "function _backtestReal(cfg){\n"
    "  try{\n"
    "    var candles=window.S&&window.S.candles;\n"
    "    var signals=window.S&&window.S.hvnSignals;\n"
    "    if(!candles||candles.length<50)return null;\n"
    "    if(!signals||!signals.length)return null;\n"
    "    /* ── real path — iterate signals, walk candles ── */\n"
    "    var riskPct=parseFloat(cfg.risk)||1.0;\n"
    "    var slMode=cfg.sl||'wick';\n"
    "    var tpMode=cfg.tp||'hvn';\n"
    "    var maxCandles=40;\n"
    "    /* period filter — auto-detect timestamp unit */\n"
    "    var _refT=candles[candles.length-1].t||0;\n"
    "    var _tScale=_refT>9999999999?1:1000; /* 1=ms, 1000=s */\n"
    "    var _ftFrom=0,_ftTo=Infinity;\n"
    "    if(cfg.dateFrom&&cfg.dateTo){\n"
    "      _ftFrom=new Date(cfg.dateFrom).getTime()/(_tScale===1?1:1000);\n"
    "      _ftTo=(new Date(cfg.dateTo).getTime()+86400000)/(_tScale===1?1:1000);\n"
    "    }else if(cfg.period){\n"
    "      var _pdSec=Math.max(1,parseInt(cfg.period)||30)*86400;\n"
    "      _ftTo=_refT;_ftFrom=_refT-(_tScale===1?_pdSec*1000:_pdSec);\n"
    "    }\n"
    "    var trades=[],eq=[100];\n"
    "    signals.forEach(function(sig){\n"
    "      if(!sig||!sig.entryPrice)return;\n"
    "      if(_ftFrom>0&&(sig.timestamp<_ftFrom||sig.timestamp>_ftTo))return;\n"
    "      var entry=sig.entryPrice;\n"
    "      var isLong=sig.side==='LONG';\n"
    "      /* SL */\n"
    "      var sl;\n"
    "      if(slMode==='wick'){sl=isLong?sig.candle.l:sig.candle.h;}\n"
    "      else if(slMode==='hvn'){var zone=sig.hvnZone||{lo:entry*0.998,hi:entry*1.002};sl=isLong?zone.lo:zone.hi;}\n"
    "      else{var atr=entry*0.005;sl=isLong?entry-atr:entry+atr;}\n"
    "      var slDist=Math.abs(entry-sl)||entry*0.002;\n"
    "      /* TP */\n"
    "      var tp;\n"
    "      if(tpMode==='1r'){tp=isLong?entry+slDist:entry-slDist;}\n"
    "      else if(tpMode==='1.5r'){tp=isLong?entry+slDist*1.5:entry-slDist*1.5;}\n"
    "      else if(tpMode==='2r'){tp=isLong?entry+slDist*2:entry-slDist*2;}\n"
    "      else if(typeof tpMode==='string'&&tpMode.indexOf('pct')>-1){var _pctV=parseFloat(tpMode)/100;tp=isLong?entry*(1+_pctV):entry*(1-_pctV);}\n"
    "      else{/* next HVN */var nz=sig.nextHvnZone||{lo:entry*(isLong?1.012:0.988)};tp=isLong?nz.lo:nz.hi||entry*(isLong?1.012:0.988);}\n"
    "      /* walk candles */\n"
    "      var sigIdx=sig.idx!==undefined?sig.idx:\n"
    "        candles.findIndex(function(c){return c.t>=sig.timestamp;});\n"
    "      if(sigIdx<0)return;\n"
    "      var outcome='timeout',exitPrice=entry;\n"
    "      for(var k=sigIdx+1;k<Math.min(sigIdx+maxCandles,candles.length);k++){\n"
    "        var c=candles[k];\n"
    "        if(isLong){\n"
    "          if(c.l<=sl){outcome='loss';exitPrice=sl;break;}\n"
    "          if(c.h>=tp){outcome='win';exitPrice=tp;break;}\n"
    "        }else{\n"
    "          if(c.h>=sl){outcome='loss';exitPrice=sl;break;}\n"
    "          if(c.l<=tp){outcome='win';exitPrice=tp;break;}\n"
    "        }\n"
    "      }\n"
    "      var rMult;\n"
    "      if(outcome==='win'){rMult=Math.abs(exitPrice-entry)/slDist;}\n"
    "      else if(outcome==='loss'){rMult=-1;}\n"
    "      else{var _tmo=isLong?(exitPrice-entry):(entry-exitPrice);rMult=_tmo/slDist;}\n"
    "      var pnl=rMult*riskPct;\n"
    "      trades.push({outcome:outcome,pnl:pnl});\n"
    "      var prev=eq[eq.length-1];\n"
    "      eq.push(Math.max(10,prev+pnl));\n"
    "    });\n"
    "    if(!trades.length)return null;\n"
    "    var wins=trades.filter(function(t){return t.outcome==='win';}).length;\n"
    "    var losses=trades.filter(function(t){return t.outcome==='loss';}).length;\n"
    "    var be=trades.filter(function(t){return t.outcome==='timeout';}).length;\n"
    "    var totalPnl=trades.reduce(function(a,t){return a+t.pnl;},0);\n"
    "    var grossW=trades.filter(function(t){return t.pnl>0;}).reduce(function(a,t){return a+t.pnl;},0);\n"
    "    var grossL=Math.abs(trades.filter(function(t){return t.pnl<0;}).reduce(function(a,t){return a+t.pnl;},0));\n"
    "    var wr=wins/trades.length;\n"
    "    var pf=grossL>0?grossW/grossL:grossW>0?9.99:0;\n"
    "    var _pk=eq[0],_mDD=0;\n"
    "    for(var _ei=1;_ei<eq.length;_ei++){if(eq[_ei]>_pk)_pk=eq[_ei];var _d=(_pk-eq[_ei])/_pk*100;if(_d>_mDD)_mDD=_d;}\n"
    "    var dd=-_mDD;\n"
    "    return{\n"
    "      trades:trades.length,wins:wins,losses:losses,be:be,\n"
    "      wr:(wr*100).toFixed(2),pf:pf.toFixed(2),\n"
    "      dd:dd.toFixed(2),ret:(totalPnl>=0?'+':'')+totalPnl.toFixed(2),\n"
    "      avg:((totalPnl/trades.length)>=0?'+':'')+(totalPnl/trades.length).toFixed(2),\n"
    "      eq:eq,longs:0,shorts:0,lwR:'—',swR:'—',\n"
    "      bestDir:'—',bestSess:'—',cfg:cfg,isReal:true\n"
    "    };\n"
    "  }catch(e){return null;}\n"
    "}"
)
NEW_BRT = (
    "/* real backtest: generates signals internally from candles+zones (Beta 0.117) */\n"
    "function _backtestReal(cfg,_preCandles,_preZones){\n"
    "  try{\n"
    "    var candles=_preCandles||(window.S&&window.S.candles)||[];\n"
    "    if(candles.length<50)return null;\n"
    "    var zones=_preZones;\n"
    "    if(!zones){\n"
    "      zones=window.__dvlComputeHVNFromCS?window.__dvlComputeHVNFromCS(candles):\n"
    "        (window.__hvnZones?window.__hvnZones():[]);\n"
    "    }\n"
    "    if(!zones||!zones.length)return null;\n"
    "    /* generate signals internally from candles+zones — no dependency on plotted signals */\n"
    "    var sigCfg={\n"
    "      wickSens:parseFloat(cfg.wickSens)||45,\n"
    "      cooldown:parseInt(cfg.cons)||5,\n"
    "      allowLat:true,\n"
    "      diveMin:parseInt(cfg.diveMin)||2,\n"
    "      mode:cfg.mode||'wick',\n"
    "      volSpike:cfg.volSpike||'off',\n"
    "      hvnMinAtr:parseFloat(cfg.hvnMinAtr)||0\n"
    "    };\n"
    "    var signals=_dvlGenHVNSigs(candles,zones,sigCfg);\n"
    "    if(!signals.length)return null;\n"
    "    /* period filter — auto-detect timestamp unit */\n"
    "    var _refT=candles[candles.length-1].t||0;\n"
    "    var _tScale=_refT>9999999999?1:1000;\n"
    "    var _ftFrom=0,_ftTo=Infinity;\n"
    "    if(cfg.dateFrom&&cfg.dateTo){\n"
    "      _ftFrom=new Date(cfg.dateFrom).getTime()/(_tScale===1?1:1000);\n"
    "      _ftTo=(new Date(cfg.dateTo).getTime()+86400000)/(_tScale===1?1:1000);\n"
    "    }else if(cfg.period){\n"
    "      var _pdSec=Math.max(1,parseInt(cfg.period)||30)*86400;\n"
    "      _ftTo=_refT;_ftFrom=_refT-(_tScale===1?_pdSec*1000:_pdSec);\n"
    "    }\n"
    "    var riskPct=parseFloat(cfg.risk)||1.0;\n"
    "    var slMode=cfg.sl||'wick';\n"
    "    var tpMode=cfg.tp||'hvn';\n"
    "    var maxCdls=40;\n"
    "    var trades=[],eq=[100];\n"
    "    signals.forEach(function(sig){\n"
    "      if(!sig||!sig.entryPrice)return;\n"
    "      if(_ftFrom>0&&(sig.timestamp<_ftFrom||sig.timestamp>_ftTo))return;\n"
    "      var entry=sig.entryPrice,isLong=sig.side==='LONG';\n"
    "      var sl;\n"
    "      if(slMode==='wick'){sl=isLong?sig.candle.l:sig.candle.h;}\n"
    "      else if(slMode==='hvn'){var _z=sig.hvnZone||{lo:entry*0.998,hi:entry*1.002};sl=isLong?_z.lo:_z.hi;}\n"
    "      else{var atr=entry*0.005;sl=isLong?entry-atr:entry+atr;}\n"
    "      var slDist=Math.abs(entry-sl)||entry*0.002;\n"
    "      var tp;\n"
    "      if(tpMode==='1r'){tp=isLong?entry+slDist:entry-slDist;}\n"
    "      else if(tpMode==='1.5r'){tp=isLong?entry+slDist*1.5:entry-slDist*1.5;}\n"
    "      else if(tpMode==='2r'){tp=isLong?entry+slDist*2:entry-slDist*2;}\n"
    "      else if(typeof tpMode==='string'&&tpMode.indexOf('pct')>-1){var _pV=parseFloat(tpMode)/100;tp=isLong?entry*(1+_pV):entry*(1-_pV);}\n"
    "      else{var nz=sig.nextHvnZone||{lo:entry*(isLong?1.012:0.988)};tp=isLong?nz.lo:nz.hi||entry*(isLong?1.012:0.988);}\n"
    "      var sigIdx=sig.idx!==undefined?sig.idx:\n"
    "        candles.findIndex(function(c){return c.t>=sig.timestamp;});\n"
    "      if(sigIdx<0)return;\n"
    "      var outcome='timeout',exitPrice=entry;\n"
    "      for(var k=sigIdx+1;k<Math.min(sigIdx+maxCdls,candles.length);k++){\n"
    "        var c=candles[k];\n"
    "        /* conservative: check SL before TP when both hit same candle */\n"
    "        if(isLong){if(c.l<=sl){outcome='loss';exitPrice=sl;break;}if(c.h>=tp){outcome='win';exitPrice=tp;break;}}\n"
    "        else{if(c.h>=sl){outcome='loss';exitPrice=sl;break;}if(c.l<=tp){outcome='win';exitPrice=tp;break;}}\n"
    "      }\n"
    "      var rMult;\n"
    "      if(outcome==='win'){rMult=Math.abs(exitPrice-entry)/slDist;}\n"
    "      else if(outcome==='loss'){rMult=-1;}\n"
    "      else{var _tmo=isLong?(exitPrice-entry):(entry-exitPrice);rMult=_tmo/slDist;}\n"
    "      trades.push({outcome:outcome,pnl:rMult*riskPct});\n"
    "      var prev=eq[eq.length-1];eq.push(Math.max(10,prev+rMult*riskPct));\n"
    "    });\n"
    "    if(!trades.length)return null;\n"
    "    var wins=trades.filter(function(t){return t.outcome==='win';}).length;\n"
    "    var losses=trades.filter(function(t){return t.outcome==='loss';}).length;\n"
    "    var be=trades.filter(function(t){return t.outcome==='timeout';}).length;\n"
    "    var totalPnl=trades.reduce(function(a,t){return a+t.pnl;},0);\n"
    "    var grossW=trades.filter(function(t){return t.pnl>0;}).reduce(function(a,t){return a+t.pnl;},0);\n"
    "    var grossL=Math.abs(trades.filter(function(t){return t.pnl<0;}).reduce(function(a,t){return a+t.pnl;},0));\n"
    "    var wr=wins/trades.length;\n"
    "    var pf=grossL>0?grossW/grossL:grossW>0?9.99:0;\n"
    "    var _pk=eq[0],_mDD=0;\n"
    "    for(var _ei=1;_ei<eq.length;_ei++){if(eq[_ei]>_pk)_pk=eq[_ei];var _d=(_pk-eq[_ei])/_pk*100;if(_d>_mDD)_mDD=_d;}\n"
    "    var dd=-_mDD;\n"
    "    return{\n"
    "      trades:trades.length,wins:wins,losses:losses,be:be,\n"
    "      wr:(wr*100).toFixed(2),pf:pf.toFixed(2),\n"
    "      dd:dd.toFixed(2),ret:(totalPnl>=0?'+':'')+totalPnl.toFixed(2),\n"
    "      avg:((totalPnl/trades.length)>=0?'+':'')+(totalPnl/trades.length).toFixed(2),\n"
    "      eq:eq,longs:0,shorts:0,lwR:'—',swR:'—',\n"
    "      bestDir:'—',bestSess:'—',cfg:cfg,isReal:true,\n"
    "      dataSource:_preCandles?'extended':'chart',candleCount:candles.length\n"
    "    };\n"
    "  }catch(e){return null;}\n"
    "}"
)
assert OLD_BRT in html, '_backtestReal old function not found'
html = html.replace(OLD_BRT, NEW_BRT, 1)

# ── 8. make _backtest return null instead of mocks ────────────────────────────
OLD_BTEST = (
    "function _backtest(cfg){\n"
    "  /* try real data first */\n"
    "  var real=_backtestReal(cfg);\n"
    "  if(real)return real;\n"
    "\n"
    "  /* Trend Break mock */\n"
    "  if(cfg.signalType==='trendBreak')return _backtestTrendBreak(cfg);\n"
    "\n"
    "  /* FVG Confluence mock */\n"
    "  if(cfg.signalType==='fvgConf')return _backtestFVG(cfg);"
)
NEW_BTEST = (
    "function _backtest(cfg){\n"
    "  /* real data only — no mock fallback (Beta 0.117) */\n"
    "  var real=_backtestReal(cfg);\n"
    "  if(real)return real;\n"
    "  /* FVG / TrendBreak: no real signal generator yet */\n"
    "  if(cfg.signalType==='trendBreak'||cfg.signalType==='fvgConf')return null;"
)
assert OLD_BTEST in html, '_backtest function anchor not found'
html = html.replace(OLD_BTEST, NEW_BTEST, 1)

# ── 9. replace button click handler with async version ────────────────────────
OLD_BTN = (
    "/* backtest run */\n"
    "var btBtn=_g('dvlSTRunBT');\n"
    "if(btBtn){\n"
    "  btBtn.addEventListener('click',function(){\n"
    "    /* guard: require real HVN signals */\n"
    "    var _gnCnt=(window.S&&window.S.hvnSignals)?\n"
    "      window.S.hvnSignals.filter(function(s){return s&&s.entryPrice;}).length:0;\n"
    "    if(_gnCnt===0){\n"
    "      var _res0=_g('dvlSTResults'),_db0=_g('dvlSTDataBadge'),_dn0=_g('dvlSTDetNote');\n"
    "      if(_res0)_res0.style.display='block';\n"
    "      if(_db0){_db0.style.display='inline-flex';_db0.textContent='SEM SINAIS';\n"
    "        _db0.style.background='rgba(255,77,106,.08)';\n"
    "        _db0.style.color='#ff4d6a';_db0.style.borderColor='rgba(255,77,106,.25)';}\n"
    "      if(_dn0){_dn0.style.display='';\n"
    "        _dn0.textContent='Nenhum sinal real carregado. Ative o HVN Signals e aguarde sinais no gr\xe1fico para rodar o backtest real.';\n"
    "        _dn0.style.color='rgba(255,77,106,.8)';}\n"
    "      _updateSigStatus();return;\n"
    "    }\n"
    "    btBtn.disabled=true;\n"
    "    btBtn.innerHTML='<svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" width=\"12\" height=\"12\"><circle cx=\"12\" cy=\"12\" r=\"10\"/></svg> CALCULANDO...';\n"
    "    setTimeout(function(){\n"
    "      var _stPer=(_g('stPeriod')||{value:'30'}).value;\n"
    "      var _stFrom=(_g('stDateFrom')||{value:''}).value;\n"
    "      var _stTo=(_g('stDateTo')||{value:''}).value;\n"
    "      var _stDays=_stPer==='custom'?\n"
    "        ((_stFrom&&_stTo)?Math.max(1,Math.round((new Date(_stTo)-new Date(_stFrom))/86400000)):365)\n"
    "        :parseInt(_stPer)||30;\n"
    "      var cfg={\n"
    "        wickSens:(_g('stWickSens')||{value:'45'}).value,\n"
    "        trend:(_g('stFTrend')||{value:'20'}).value,\n"
    "        flow:(_g('stFFlow')||{value:'20'}).value,\n"
    "        nextHVN:(_g('stNextHVN')||{value:'0.35'}).value,\n"
    "        sl:(_g('stSL')||{value:'wick'}).value,\n"
    "        tp:(_g('stTP')||{value:'hvn'}).value,\n"
    "        risk:(_g('stRisk')||{value:'1.0'}).value,\n"
    "        be:(_g('stBE')||{value:'off'}).value,\n"
    "        tf:(_g('stTf')||{value:'5m'}).value,\n"
    "        period:String(_stDays),\n"
    "        dateFrom:_stPer==='custom'?_stFrom:'',\n"
    "        dateTo:_stPer==='custom'?_stTo:'',\n"
    "        mode:(_g('stMode')||{value:'wick'}).value,\n"
    "        diveMin:parseInt((_g('stDiveMin')||{value:'2'}).value)||2,\n"
    "        signalType:(_g('stInd')||{value:'hvnSignals'}).value,\n"
    "        fvgMinAtr:parseFloat((_g('stFvgMinAtr')||{value:'0.08'}).value)||0.08,\n"
    "        fvgMit:(_g('stFvgMit')||{value:'wick'}).value,\n"
    "        fvgReact:parseInt((_g('stFvgReact')||{value:'1'}).value)===1,\n"
    "        fvgReentry:parseInt((_g('stFvgReentry')||{value:'1'}).value)===1,\n"
    "        fvgMaxAge:parseInt((_g('stFvgMaxAge')||{value:'300'}).value)||0,\n"
    "        tbFast:parseInt((_g('stTBFast')||{value:'3'}).value)||3,\n"
    "        tbSlow:parseInt((_g('stTBSlow')||{value:'10'}).value)||10,\n"
    "        tbBias:parseFloat((_g('stTBBias')||{value:'5'}).value)||5,\n"
    "        tbExit:(_g('stTBExit')||{value:'flip'}).value,\n"
    "        trendFilter:(_g('stTBFilterMode')||{value:'off'}).value,\n"
    "        tfBias:parseFloat((_g('stTBFilterBias')||{value:'5'}).value)||5,\n"
    "        tfFast:parseInt((_g('stTBFilterFast')||{value:'3'}).value)||3,\n"
    "        tfSlow:parseInt((_g('stTBFilterSlow')||{value:'10'}).value)||10,\n"
    "        hvnMinAtr:parseFloat((_g('stHvnMinAtr')||{value:'0'}).value)||0,\n"
    "      };\n"
    "      var res=_backtestReal(cfg);\n"
    "      if(!res||!res.trades){\n"
    "        var _rbn=_g('dvlSTResults'),_dbn=_g('dvlSTDataBadge'),_dnn=_g('dvlSTDetNote');\n"
    "        if(_rbn)_rbn.style.display='block';\n"
    "        if(_dbn){_dbn.style.display='inline-flex';_dbn.textContent='SEM TRADES';\n"
    "          _dbn.style.background='rgba(255,180,0,.1)';\n"
    "          _dbn.style.color='#ffb400';_dbn.style.borderColor='rgba(255,180,0,.28)';}\n"
    "        if(_dnn){_dnn.style.display='';\n"
    "          _dnn.textContent='Nenhum trade encontrado no per\xedodo selecionado. Ajuste o per\xedodo ou verifique os filtros.';\n"
    "          _dnn.style.color='rgba(255,180,0,.7)';}\n"
    "        btBtn.disabled=false;\n"
    "        btBtn.innerHTML='<svg viewBox=\"0 0 24 24\" fill=\"currentColor\" width=\"12\" height=\"12\"><polygon points=\"5,3 19,12 5,21\"/></svg> RODAR BACKTEST';\n"
    "        _updateSigStatus();return;\n"
    "      }\n"
    "      _renderResults(res);\n"
    "      var _sCnt2=(window.S&&window.S.hvnSignals)?\n"
    "        window.S.hvnSignals.filter(function(s){return s&&s.entryPrice;}).length:0;\n"
    "      var db=_g('dvlSTDataBadge'),dn=_g('dvlSTDetNote');\n"
    "      if(db){db.style.display='inline-flex';db.textContent='REAL DATA';\n"
    "        db.style.background='rgba(0,200,100,.08)';\n"
    "        db.style.color='#00c864';db.style.borderColor='rgba(0,200,100,.25)';}\n"
    "      if(dn){dn.style.display='';\n"
    "        dn.textContent='Backtest usando sinais reais do HVN Signals. Signals loaded: '+_sCnt2;\n"
    "        dn.style.color='rgba(0,200,100,.8)';}\n"
    "      _updateSigStatus();\n"
    "      btBtn.disabled=false;\n"
    "      btBtn.innerHTML='<svg viewBox=\"0 0 24 24\" fill=\"currentColor\" width=\"12\" height=\"12\"><polygon points=\"5,3 19,12 5,21\"/></svg> RODAR BACKTEST';\n"
    "      var r=_g('dvlSTResults');if(r){setTimeout(function(){r.scrollIntoView({behavior:'smooth',block:'nearest'});},100);}\n"
    "    },750);\n"
    "  });\n"
    "}"
)
NEW_BTN = (
    "/* backtest run — async: fetches historical candles, generates signals internally */\n"
    "var btBtn=_g('dvlSTRunBT');\n"
    "if(btBtn){\n"
    "  btBtn.addEventListener('click',async function(){\n"
    "    btBtn.disabled=true;\n"
    "    btBtn.innerHTML='<svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" width=\"12\" height=\"12\"><circle cx=\"12\" cy=\"12\" r=\"10\"/></svg> CARREGANDO...';\n"
    "    var _dn0=_g('dvlSTDetNote');\n"
    "    if(_dn0){_dn0.style.display='';_dn0.textContent='Buscando hist\xf3rico real...';_dn0.style.color='#344a62';}\n"
    "    try{\n"
    "      var _stPer=(_g('stPeriod')||{value:'30'}).value;\n"
    "      var _stFrom=(_g('stDateFrom')||{value:''}).value;\n"
    "      var _stTo=(_g('stDateTo')||{value:''}).value;\n"
    "      var _stDays=_stPer==='custom'?\n"
    "        ((_stFrom&&_stTo)?Math.max(1,Math.round((new Date(_stTo)-new Date(_stFrom))/86400000)):365)\n"
    "        :parseInt(_stPer)||30;\n"
    "      var cfg={\n"
    "        wickSens:(_g('stWickSens')||{value:'45'}).value,\n"
    "        trend:(_g('stFTrend')||{value:'20'}).value,\n"
    "        flow:(_g('stFFlow')||{value:'20'}).value,\n"
    "        nextHVN:(_g('stNextHVN')||{value:'0.35'}).value,\n"
    "        sl:(_g('stSL')||{value:'wick'}).value,\n"
    "        tp:(_g('stTP')||{value:'hvn'}).value,\n"
    "        risk:(_g('stRisk')||{value:'1.0'}).value,\n"
    "        be:(_g('stBE')||{value:'off'}).value,\n"
    "        tf:(_g('stTf')||{value:'5m'}).value,\n"
    "        period:String(_stDays),\n"
    "        dateFrom:_stPer==='custom'?_stFrom:'',\n"
    "        dateTo:_stPer==='custom'?_stTo:'',\n"
    "        mode:(_g('stMode')||{value:'wick'}).value,\n"
    "        diveMin:parseInt((_g('stDiveMin')||{value:'2'}).value)||2,\n"
    "        volSpike:(_g('stFVol')||{value:'off'}).value,\n"
    "        hvnMinAtr:parseFloat((_g('stHvnMinAtr')||{value:'0'}).value)||0,\n"
    "        cons:parseInt((_g('stMaxCandles')||{value:'8'}).value)||8,\n"
    "        signalType:(_g('stInd')||{value:'hvnSignals'}).value,\n"
    "        fvgMinAtr:parseFloat((_g('stFvgMinAtr')||{value:'0.08'}).value)||0.08,\n"
    "        fvgMit:(_g('stFvgMit')||{value:'wick'}).value,\n"
    "        fvgReact:parseInt((_g('stFvgReact')||{value:'1'}).value)===1,\n"
    "        fvgReentry:parseInt((_g('stFvgReentry')||{value:'1'}).value)===1,\n"
    "        fvgMaxAge:parseInt((_g('stFvgMaxAge')||{value:'300'}).value)||0,\n"
    "        tbFast:parseInt((_g('stTBFast')||{value:'3'}).value)||3,\n"
    "        tbSlow:parseInt((_g('stTBSlow')||{value:'10'}).value)||10,\n"
    "        tbBias:parseFloat((_g('stTBBias')||{value:'5'}).value)||5,\n"
    "        tbExit:(_g('stTBExit')||{value:'flip'}).value,\n"
    "        trendFilter:(_g('stTBFilterMode')||{value:'off'}).value,\n"
    "        tfBias:parseFloat((_g('stTBFilterBias')||{value:'5'}).value)||5,\n"
    "        tfFast:parseInt((_g('stTBFilterFast')||{value:'3'}).value)||3,\n"
    "        tfSlow:parseInt((_g('stTBFilterSlow')||{value:'10'}).value)||10,\n"
    "      };\n"
    "      var sym=(window.S&&window.S.sym)||'BTCUSDT';\n"
    "      var tf=(window.S&&window.S.tf)||'5m';\n"
    "      var candles,dataSource='chart';\n"
    "      try{\n"
    "        candles=await _dvlFetchBTCandles(sym,tf,_stDays,cfg.dateFrom,cfg.dateTo);\n"
    "        dataSource='fetched';\n"
    "      }catch(e){\n"
    "        candles=(window.S&&window.S.candles)||[];\n"
    "        dataSource='chart';\n"
    "      }\n"
    "      var db=_g('dvlSTDataBadge'),dn=_g('dvlSTDetNote'),res0=_g('dvlSTResults');\n"
    "      function _setBadge(txt,clr,bg,bd,msg,msgClr){\n"
    "        if(res0)res0.style.display='block';\n"
    "        if(db){db.style.display='inline-flex';db.textContent=txt;\n"
    "          db.style.background=bg;db.style.color=clr;db.style.borderColor=bd;}\n"
    "        if(dn){dn.style.display='';dn.textContent=msg;dn.style.color=msgClr;}\n"
    "      }\n"
    "      if(!candles||candles.length<50){\n"
    "        _setBadge('NO HISTORY','#ff4d6a','rgba(255,77,106,.08)','rgba(255,77,106,.25)',\n"
    "          'Hist\xf3rico insuficiente para backtest real. Carregue mais candles ou aumente o per\xedodo.',\n"
    "          'rgba(255,77,106,.8)');\n"
    "        return;\n"
    "      }\n"
    "      var zones=window.__dvlComputeHVNFromCS?window.__dvlComputeHVNFromCS(candles):\n"
    "        (window.__hvnZones?window.__hvnZones():[]);\n"
    "      if(!zones||!zones.length){\n"
    "        _setBadge('NO HISTORY','#ff4d6a','rgba(255,77,106,.08)','rgba(255,77,106,.25)',\n"
    "          'Sem zonas HVN calculadas. Ative o Vol Zones e recarregue o gr\xe1fico.',\n"
    "          'rgba(255,77,106,.8)');\n"
    "        return;\n"
    "      }\n"
    "      var res=_backtestReal(cfg,candles,zones);\n"
    "      var _cLen=candles.length,_isLim=_cLen<300;\n"
    "      if(!res||!res.trades){\n"
    "        var _noTxt=_isLim?'LIMITED HISTORY':'SEM TRADES';\n"
    "        _setBadge(_noTxt,'#ffb400','rgba(255,180,0,.1)','rgba(255,180,0,.28)',\n"
    "          _isLim?'Hist\xf3rico curto ('+_cLen+' candles). Resultado pode ser pouco representativo.':\n"
    "            'Nenhum trade encontrado no per\xedodo. Ajuste o per\xedodo ou os filtros.',\n"
    "          'rgba(255,180,0,.7)');\n"
    "        return;\n"
    "      }\n"
    "      _renderResults(res);\n"
    "      var _bt=_isLim?'LIMITED HISTORY':(dataSource==='fetched'?'REAL HISTORY':'CHART DATA');\n"
    "      var _bc=_isLim?'#ffb400':(dataSource==='fetched'?'#00c864':'#00b4ff');\n"
    "      var _bb=_isLim?'rgba(255,180,0,.1)':(dataSource==='fetched'?'rgba(0,200,100,.08)':'rgba(0,180,255,.08)');\n"
    "      var _bbd=_isLim?'rgba(255,180,0,.28)':(dataSource==='fetched'?'rgba(0,200,100,.25)':'rgba(0,180,255,.25)');\n"
    "      var _info=(dataSource==='fetched'?'Backtest real: '+_cLen+' candles hist\xf3ricos. ':\n"
    "        'Backtest: '+_cLen+' candles do gr\xe1fico. ')+'Sinais gerados internamente: '+res.trades+' trades.';\n"
    "      _setBadge(_bt,_bc,_bb,_bbd,_info,_bc==='#00c864'?'rgba(0,200,100,.8)':_bc==='#00b4ff'?'rgba(0,180,255,.8)':'rgba(255,180,0,.7)');\n"
    "      _updateSigStatus();\n"
    "      var _r=_g('dvlSTResults');if(_r){setTimeout(function(){_r.scrollIntoView({behavior:'smooth',block:'nearest'});},100);}\n"
    "    }finally{\n"
    "      btBtn.disabled=false;\n"
    "      btBtn.innerHTML='<svg viewBox=\"0 0 24 24\" fill=\"currentColor\" width=\"12\" height=\"12\"><polygon points=\"5,3 19,12 5,21\"/></svg> RODAR BACKTEST';\n"
    "    }\n"
    "  });\n"
    "}"
)
assert OLD_BTN in html, 'button click handler not found'
html = html.replace(OLD_BTN, NEW_BTN, 1)

# ── 10. replace _runOptimizer with real per-combo signal generation ───────────
_OPT_GEAR = (
    "'<svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\" width=\"12\" height=\"12\">"
    "<circle cx=\"12\" cy=\"12\" r=\"3\"/>"
    "<path d=\"M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 0 1-2.83 2.83l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-4 0v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 0 1-2.83-2.83l.06-.06A1.65 1.65 0 0 0 4.68 15a1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1 0-4h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 0 1 2.83-2.83l.06.06A1.65 1.65 0 0 0 9 4.68a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 4 0v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 0 1 2.83 2.83l-.06.06A1.65 1.65 0 0 0 19.4 9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 0 4h-.09a1.65 1.65 0 0 0-1.51 1z\"/></svg> AUTO OPTIMIZE'"
)
OLD_OPT = (
    "function _runOptimizer(){\n"
    "  /* guard: require real signals */\n"
    "  var _optSigCnt=(window.S&&window.S.hvnSignals)?\n"
    "    window.S.hvnSignals.filter(function(s){return s&&s.entryPrice;}).length:0;\n"
    "  if(_optSigCnt===0){\n"
    "    var _ost=_g('dvlSTOptStatus');\n"
    "    if(_ost){_ost.style.color='#ff4d6a';\n"
    "      _ost.textContent='Optimizer precisa de sinais reais. Ative o HVN Signals e aguarde sinais no gr\xe1fico.';}\n"
    "    return;\n"
    "  }\n"
    "  var bar=_g('dvlSTOptBar'),prog=_g('dvlSTOptProg'),status=_g('dvlSTOptStatus');\n"
    "  var rw=_g('dvlSTRankWrap'),rl=_g('dvlSTRankList'),runBtn=_g('dvlSTRunOpt');\n"
    "  if(!runBtn)return;\n"
    "  runBtn.disabled=true;\n"
    "  runBtn.innerHTML='<svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" width=\"12\" height=\"12\"><circle cx=\"12\" cy=\"12\" r=\"10\"/></svg> OTIMIZANDO...';\n"
    "  if(prog)prog.classList.add('show');\n"
    "  if(rw)rw.style.display='none';\n"
    "  for(var _k in _btCache)delete _btCache[_k];\n"
    "  var _optIndVal=(_g('stInd')||{value:'hvnSignals'}).value;\n"
    "  var _isFvgOpt=_optIndVal==='fvgConf',_isTBOpt=_optIndVal==='trendBreak';\n"
    "  var _COMBOS=_isFvgOpt?FVG_OPT_COMBOS:(_isTBOpt?TB_OPT_COMBOS:OPT_COMBOS);\n"
    "  var _optPeriod=String(parseInt((_g('stOptPeriod')||{value:'30'}).value)||30);\n"
    "  var _optTf=(_g('stOptTf')||{value:'5m'}).value||'5m';\n"
    "  var results=[],total=_COMBOS.length,done=0;\n"
    "  function step(){\n"
    "    if(done>=total){\n"
    "      _allOptResults=results;\n"
    "      _reRankResults();\n"
    "      runBtn.disabled=false;\n"
    "      runBtn.innerHTML=" + _OPT_GEAR + ";\n"
    "      if(prog)prog.classList.remove('show');\n"
    "      if(status)status.textContent='';\n"
    "      return;\n"
    "    }\n"
    "    var batch=Math.min(15,total-done);\n"
    "    for(var _b=0;_b<batch;_b++){\n"
    "      var c=_COMBOS[done];\n"
    "      var r=_isFvgOpt?\n"
    "        _cachedBacktest({signalType:'fvgConf',trend:c.trend,flow:c.flow,volSpike:c.volSpike||'off',sl:c.sl,tp:c.tp,risk:1.0,fvgMinAtr:c.minAtr,fvgMit:c.mitMode,fvgReact:c.react,fvgReentry:c.reentry,fvgMaxAge:c.maxAge,trendFilter:c.trendFilter||'off',period:_optPeriod,tf:_optTf}):\n"
    "        (_isTBOpt?\n"
    "        _cachedBacktest({signalType:'trendBreak',tbFast:c.fast,tbSlow:c.slow,tbBias:c.bias,tbExit:c.exitMode||'flip',sl:c.sl,tp:c.tp,risk:1.0,trend:c.trend,flow:c.flow,volSpike:c.volSpike||'off',period:_optPeriod,tf:_optTf}):\n"
    "        _cachedBacktest({wickSens:c.w,trend:c.trend,flow:c.flow,nextHVN:c.hvn,sl:c.sl,tp:c.tp,risk:1.0,close:c.close,cons:c.cons,volSpike:c.volSpike||'off',mode:c.mode||'wick',diveMin:c.diveMin||2,trendFilter:c.trendFilter||'off',hvnMinAtr:c.minAtrHvn||0,period:_optPeriod,tf:c.tf||_optTf}));\n"
    "      if(r)results.push({c:c,trades:r.trades,wr:r.wr,pf:r.pf,ret:r.ret,dd:r.dd});\n"
    "      done++;\n"
    "    }\n"
    "    if(bar)bar.style.width=(done/total*100)+'%';\n"
    "    if(status)status.textContent='Testando combina\xe7\xe3o '+done+' de '+total+'...';\n"
    "    setTimeout(step,4);\n"
    "  }\n"
    "  step();\n"
    "}"
)
NEW_OPT = (
    "function _runOptimizer(){\n"
    "  var bar=_g('dvlSTOptBar'),prog=_g('dvlSTOptProg'),status=_g('dvlSTOptStatus');\n"
    "  var rw=_g('dvlSTRankWrap'),rl=_g('dvlSTRankList'),runBtn=_g('dvlSTRunOpt');\n"
    "  if(!runBtn)return;\n"
    "  var _optIndVal=(_g('stInd')||{value:'hvnSignals'}).value;\n"
    "  var _isFvgOpt=_optIndVal==='fvgConf',_isTBOpt=_optIndVal==='trendBreak';\n"
    "  if(_isFvgOpt||_isTBOpt){\n"
    "    if(status){status.style.color='#ff4d6a';\n"
    "      status.textContent='Backtest real dispon\xedvel apenas para HVN Signals. FVG e TrendBreak em desenvolvimento.';}\n"
    "    return;\n"
    "  }\n"
    "  var _optPeriod=parseInt((_g('stOptPeriod')||{value:'30'}).value)||30;\n"
    "  var _optTf=(_g('stOptTf')||{value:'5m'}).value||'5m';\n"
    "  var sym=(window.S&&window.S.sym)||'BTCUSDT';\n"
    "  runBtn.disabled=true;\n"
    "  runBtn.innerHTML='<svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" width=\"12\" height=\"12\"><circle cx=\"12\" cy=\"12\" r=\"10\"/></svg> OTIMIZANDO...';\n"
    "  if(prog)prog.classList.add('show');\n"
    "  if(rw)rw.style.display='none';\n"
    "  for(var _k in _btCache)delete _btCache[_k];\n"
    "  if(status){status.style.color='';status.textContent='Carregando hist\xf3rico real...';}\n"
    "  function _doOpt(candles,zones){\n"
    "    var results=[],total=OPT_COMBOS.length,done=0;\n"
    "    function step(){\n"
    "      if(done>=total){\n"
    "        _allOptResults=results;\n"
    "        _reRankResults();\n"
    "        runBtn.disabled=false;\n"
    "        runBtn.innerHTML=" + _OPT_GEAR + ";\n"
    "        if(prog)prog.classList.remove('show');\n"
    "        if(status)status.textContent=results.length>0?\n"
    "          'Conclu\xeddo: '+results.length+' combina\xe7\xf5es com trades reais.':\n"
    "          'Nenhuma combina\xe7\xe3o gerou trades. Verifique o per\xedodo e par\xe2metros.';\n"
    "        return;\n"
    "      }\n"
    "      var batch=Math.min(15,total-done);\n"
    "      for(var _b=0;_b<batch;_b++){\n"
    "        var c=OPT_COMBOS[done];\n"
    "        var comboCfg={wickSens:c.w,trend:c.trend,flow:c.flow,nextHVN:c.hvn,\n"
    "          sl:c.sl,tp:c.tp,risk:1.0,cons:c.cons,volSpike:c.volSpike||'off',\n"
    "          mode:c.mode||'wick',diveMin:c.diveMin||2,hvnMinAtr:c.minAtrHvn||0,\n"
    "          period:String(_optPeriod),tf:c.tf||_optTf,trendFilter:c.trendFilter||'off'};\n"
    "        var r=_backtestReal(comboCfg,candles,zones);\n"
    "        if(r&&r.trades>0)results.push({c:c,trades:r.trades,wr:r.wr,pf:r.pf,ret:r.ret,dd:r.dd});\n"
    "        done++;\n"
    "      }\n"
    "      if(bar)bar.style.width=(done/total*100)+'%';\n"
    "      if(status)status.textContent='Testando combina\xe7\xe3o '+done+' de '+total+'...';\n"
    "      setTimeout(step,4);\n"
    "    }\n"
    "    step();\n"
    "  }\n"
    "  function _optFail(msg){\n"
    "    if(status){status.style.color='#ff4d6a';status.textContent=msg;}\n"
    "    runBtn.disabled=false;\n"
    "    runBtn.innerHTML=" + _OPT_GEAR + ";\n"
    "    if(prog)prog.classList.remove('show');\n"
    "  }\n"
    "  _dvlFetchBTCandles(sym,_optTf,_optPeriod,'','').then(function(candles){\n"
    "    var zones=window.__dvlComputeHVNFromCS?window.__dvlComputeHVNFromCS(candles):\n"
    "      (window.__hvnZones?window.__hvnZones():[]);\n"
    "    if(!candles||candles.length<50)return _optFail('Hist\xf3rico insuficiente ('+((candles&&candles.length)||0)+' candles). Aumente o per\xedodo.');\n"
    "    if(!zones||!zones.length)return _optFail('Sem zonas HVN calculadas. Ative o Vol Zones e recarregue.');\n"
    "    if(status)status.textContent='Hist\xf3rico: '+candles.length+' candles. Gerando sinais...';\n"
    "    _doOpt(candles,zones);\n"
    "  }).catch(function(){\n"
    "    var candles=(window.S&&window.S.candles)||[];\n"
    "    var zones=window.__dvlComputeHVNFromCS?window.__dvlComputeHVNFromCS(candles):\n"
    "      (window.__hvnZones?window.__hvnZones():[]);\n"
    "    if(!candles.length||!zones.length)return _optFail('Sem hist\xf3rico dispon\xedvel. Verifique a conex\xe3o.');\n"
    "    if(status)status.textContent='Candles do gr\xe1fico ('+candles.length+'). Gerando sinais...';\n"
    "    _doOpt(candles,zones);\n"
    "  });\n"
    "}"
)
assert OLD_OPT in html, '_runOptimizer function not found'
html = html.replace(OLD_OPT, NEW_OPT, 1)

with open(src, 'w', encoding='utf-8') as f:
    f.write(html)

print('OK: Beta 0.117 applied')
