#!/usr/bin/env python3
"""patch_150.py — Beta 0.150:
   ROOT CAUSE FIX: delta always 0 for historical candles.
   klineToCandle() sets buy:0,sell:0 (not null), so c.buy!=null was always TRUE
   → synthetic OHLCV path never ran → delta=0 → normDelta=0 → bias=0 → FLAT

   1. delta condition: (buy+sell)>0  instead of !=null
   2. drawCloud(): directional (bullish cloud below, bearish above), higher opacity
   3. event labels: compact pill, no subtitle line, 40px min spacing
   4. _compute(): debug logging (window._dvlPTDebug=true to enable)
"""
import os
os.chdir(os.path.dirname(os.path.abspath(__file__)))

with open('DepthVisionLab-v106_REAL_UI/public/index.html','r',encoding='utf-8') as f:
    html = f.read()

assert html.count('Beta 0.149') >= 10, 'Beta 0.149 not found'
html = html.replace('Beta 0.149', 'Beta 0.150')

# ── 1. CRITICAL: fix delta condition ────────────────────────────────────────────
OLD_DELTA_COND = (
    "      if(c.buy!=null&&c.sell!=null){delta[i]=(c.buy||0)-(c.sell||0);}\n"
    "      else{var range=Math.max(c.h-c.l,1e-12);delta[i]=((c.c-c.l)/range*2-1)*c.v;isSynth[i]=1;synthCount++;}"
)
assert OLD_DELTA_COND in html, 'delta condition anchor not found'
NEW_DELTA_COND = (
    "      /* hasFP: klineToCandle initialises buy=0,sell=0 (not null) for all history.\n"
    "         Checking !=null was always true → delta=0 → flat oscillator.\n"
    "         Fix: treat as real only when buy+sell > 0 (actual orderflow present). */\n"
    "      var hasFP=(c.buy||0)+(c.sell||0)>0;\n"
    "      if(hasFP){delta[i]=(c.buy||0)-(c.sell||0);}\n"
    "      else{var range=Math.max(c.h-c.l,1e-12);delta[i]=((c.c-c.l)/range*2-1)*c.v;isSynth[i]=1;synthCount++;}"
)
html = html.replace(OLD_DELTA_COND, NEW_DELTA_COND, 1)

# ── 2. debug logging before return ──────────────────────────────────────────────
OLD_RETURN = "    return {bias,pressure,normDelta,delta,aggr,pulse,atr,volMA,events,marketMode,n,synthCount,isSynth};"
assert OLD_RETURN in html, 'compute return not found'
NEW_RETURN = (
    "    /* debug: window._dvlPTDebug=true in browser console */\n"
    "    if(window._dvlPTDebug){\n"
    "      var _rc=n-synthCount,_fNZ=-1,_lNZ=-1;\n"
    "      for(var _di=0;_di<n;_di++){if(delta[_di]!==0){if(_fNZ<0)_fNZ=_di;_lNZ=_di;}}\n"
    "      var _ds=Array.from(delta),_as=Array.from(aggr),_ps=Array.from(pulse);\n"
    "      console.group('%cDVL PT','color:cyan;font-weight:bold');\n"
    "      console.log('candles:',n,'| realFP:',_rc,'| synth:',synthCount,'('+(synthCount/n*100|0)+'%)');\n"
    "      console.log('delta:',Math.min.apply(null,_ds).toFixed(4),'\\u2192',Math.max.apply(null,_ds).toFixed(4),'| first\\u22600:',_fNZ,'last:',_lNZ);\n"
    "      console.log('aggr:',Math.min.apply(null,_as).toFixed(4),'\\u2192',Math.max.apply(null,_as).toFixed(4));\n"
    "      console.log('pulse:',Math.min.apply(null,_ps).toFixed(4),'\\u2192',Math.max.apply(null,_ps).toFixed(4));\n"
    "      console.log('bias[last]:',bias[n-1].toFixed(4),'| pressure[last]:',pressure[n-1].toFixed(4));\n"
    "      console.groupEnd();\n"
    "    }\n"
    "    return {bias,pressure,normDelta,delta,aggr,pulse,atr,volMA,events,marketMode,n,synthCount,isSynth};"
)
html = html.replace(OLD_RETURN, NEW_RETURN, 1)

# ── 3. drawCloud() — directional bias-aware 3-layer filled band ─────────────────
OLD_CLOUD = (
    "  /* ── CLOUD (before candles) — continuous 3-layer band, smoothed ──────────── */\n"
    "  function drawCloud(ctx,W,H,AllV,sc,x,bw){\n"
    "    if(!window.S||!S.inds.pressureTrail||!S.candles.length)return;\n"
    "    var cfg=_getCfg();if(!cfg.showCloud)return;\n"
    "    var cs=S.candles,n=cs.length;\n"
    "    if(!_cache){var ck=_ck(cs,cfg);if(_cKey!==ck){_cache=_compute(cs,cfg);_cKey=ck;}}\n"
    "    if(!_cache)return;\n"
    "    var res=_cache;\n"
    "\n"
    "    var from=Math.max(0,AllV.a),to=Math.min(n-1,AllV.b);\n"
    "    if(to<from+1)return;\n"
    "    var len=to-from+1;\n"
    "\n"
    "    /* 3 concentric layers: outer (wide+translucent) → mid → core (narrow+opaque) */\n"
    "    var LYR=[\n"
    "      {top:new Float32Array(len),bot:new Float32Array(len),hS:1.00,opM:0.70},\n"
    "      {top:new Float32Array(len),bot:new Float32Array(len),hS:0.58,opM:1.10},\n"
    "      {top:new Float32Array(len),bot:new Float32Array(len),hS:0.28,opM:1.65}\n"
    "    ];\n"
    "    for(var k=0;k<len;k++){\n"
    "      var i=from+k,at=res.atr[i]||1,p=res.pressure[i]||0;\n"
    "      var fh=at*(0.42+p*1.00); /* full half-height in price units */\n"
    "      for(var li=0;li<LYR.length;li++){\n"
    "        var h=fh*LYR[li].hS;\n"
    "        LYR[li].top[k]=sc.y(cs[i].c+h);\n"
    "        LYR[li].bot[k]=sc.y(cs[i].c-h);\n"
    "      }\n"
    "    }\n"
    "    /* 5-point smoothing on pixel bands */\n"
    "    function _sm(arr){\n"
    "      var o=new Float32Array(arr.length);\n"
    "      for(var k=0;k<arr.length;k++){\n"
    "        var s=0,cnt=0;\n"
    "        for(var j=Math.max(0,k-2);j<=Math.min(arr.length-1,k+2);j++){s+=arr[j];cnt++;}\n"
    "        o[k]=s/cnt;\n"
    "      }\n"
    "      return o;\n"
    "    }\n"
    "    for(var li=0;li<LYR.length;li++){LYR[li].top=_sm(LYR[li].top);LYR[li].bot=_sm(LYR[li].bot);}\n"
    "\n"
    "    ctx.save();\n"
    "    /* draw each layer as bias-coloured filled segments */\n"
    "    for(var li=0;li<LYR.length;li++){\n"
    "      var lyr=LYR[li];\n"
    "      var segS=0;\n"
    "      for(var k=0;k<=len;k++){\n"
    "        var isEnd=(k===len);\n"
    "        var brk=false;\n"
    "        if(!isEnd&&k>0){\n"
    "          var bs0=_biasSign(res.bias[Math.min(from+k-1,n-1)]);\n"
    "          var bs1=_biasSign(res.bias[Math.min(from+k,n-1)]);\n"
    "          brk=(bs0!==bs1);\n"
    "        }\n"
    "        if(brk||isEnd){\n"
    "          var se=k-1;\n"
    "          if(se>=segS){\n"
    "            var mi=Math.max(0,Math.min(n-1,from+Math.round((segS+se)/2)));\n"
    "            var col=_biasColor(res.bias[mi],res.pressure[mi]);\n"
    "            var op=Math.min(0.88,cfg.cloudOp*lyr.opM*(0.30+res.pressure[mi]*0.70));\n"
    "            ctx.fillStyle='rgba('+col.r+','+col.g+','+col.b+','+op.toFixed(3)+')';\n"
    "            ctx.beginPath();\n"
    "            ctx.moveTo(x(from+segS),lyr.top[segS]);\n"
    "            for(var j=segS+1;j<=se;j++)ctx.lineTo(x(from+j),lyr.top[j]);\n"
    "            for(var j=se;j>=segS;j--)ctx.lineTo(x(from+j),lyr.bot[j]);\n"
    "            ctx.closePath();ctx.fill();\n"
    "          }\n"
    "          segS=k;\n"
    "        }\n"
    "      }\n"
    "    }\n"
    "    /* synthetic history watermark */\n"
    "    if(res.synthCount>0&&res.synthCount/res.n>0.05){\n"
    "      var rp2=typeof RP==='function'?RP():68;\n"
    "      ctx.font='600 8px monospace';ctx.textAlign='right';ctx.textBaseline='top';\n"
    "      ctx.fillStyle='rgba(200,170,50,0.48)';\n"
    "      ctx.fillText('\\u007e SYNTHETIC HISTORY',W-rp2-8,4);\n"
    "    }\n"
    "    ctx.restore();\n"
    "  }"
)
assert OLD_CLOUD in html, 'drawCloud anchor not found'

NEW_CLOUD = (
    "  /* ── CLOUD (before candles) — directional bias-aware 3-layer filled band ── */\n"
    "  function drawCloud(ctx,W,H,AllV,sc,x,bw){\n"
    "    if(!window.S||!S.inds.pressureTrail||!S.candles.length)return;\n"
    "    var cfg=_getCfg();if(!cfg.showCloud)return;\n"
    "    var cs=S.candles,n=cs.length;\n"
    "    if(!_cache){var ck=_ck(cs,cfg);if(_cKey!==ck){_cache=_compute(cs,cfg);_cKey=ck;}}\n"
    "    if(!_cache)return;\n"
    "    var res=_cache;\n"
    "\n"
    "    var from=Math.max(0,AllV.a),to=Math.min(n-1,AllV.b);\n"
    "    if(to<from+1)return;\n"
    "    var len=to-from+1;\n"
    "\n"
    "    /* 3 layers: outer(wide+soft) → mid → core(tight+bright) */\n"
    "    var LYR=[\n"
    "      {top:new Float32Array(len),bot:new Float32Array(len),hS:1.00,baseOp:0.08},\n"
    "      {top:new Float32Array(len),bot:new Float32Array(len),hS:0.62,baseOp:0.16},\n"
    "      {top:new Float32Array(len),bot:new Float32Array(len),hS:0.32,baseOp:0.28}\n"
    "    ];\n"
    "    for(var k=0;k<len;k++){\n"
    "      var i=from+k,at=res.atr[i]||1,p=res.pressure[i]||0;\n"
    "      var b=Math.max(-1,Math.min(1,res.bias[i]||0));\n"
    "      /* half-band in price units */\n"
    "      var hb=at*(0.22+p*0.55);\n"
    "      /* directional offsets:\n"
    "         bullish (b→+1): cloud below close — topFrac→0 (no top ext), botFrac→1 (full bot)\n"
    "         bearish (b→-1): cloud above close — topFrac→1 (full top), botFrac→0 (no bot)\n"
    "         neutral (b= 0): symmetric ±0.5 */\n"
    "      var topFrac=0.50-b*0.50;\n"
    "      var botFrac=0.50+b*0.50;\n"
    "      for(var li=0;li<LYR.length;li++){\n"
    "        var hS=LYR[li].hS;\n"
    "        LYR[li].top[k]=sc.y(cs[i].c+hb*topFrac*hS);\n"
    "        LYR[li].bot[k]=sc.y(cs[i].c-hb*botFrac*hS);\n"
    "      }\n"
    "    }\n"
    "    /* 5-point smoothing on pixel bands */\n"
    "    function _sm(arr){\n"
    "      var o=new Float32Array(arr.length);\n"
    "      for(var k=0;k<arr.length;k++){\n"
    "        var s=0,cnt=0;\n"
    "        for(var j=Math.max(0,k-2);j<=Math.min(arr.length-1,k+2);j++){s+=arr[j];cnt++;}\n"
    "        o[k]=s/cnt;\n"
    "      }\n"
    "      return o;\n"
    "    }\n"
    "    for(var li=0;li<LYR.length;li++){LYR[li].top=_sm(LYR[li].top);LYR[li].bot=_sm(LYR[li].bot);}\n"
    "\n"
    "    ctx.save();\n"
    "    var opScale=Math.max(0.1,cfg.cloudOp/0.20);\n"
    "    for(var li=0;li<LYR.length;li++){\n"
    "      var lyr=LYR[li];\n"
    "      var segS=0;\n"
    "      for(var k=0;k<=len;k++){\n"
    "        var isEnd=(k===len);\n"
    "        var brk=false;\n"
    "        if(!isEnd&&k>0){\n"
    "          var bs0=_biasSign(res.bias[Math.min(from+k-1,n-1)]);\n"
    "          var bs1=_biasSign(res.bias[Math.min(from+k,n-1)]);\n"
    "          brk=(bs0!==bs1);\n"
    "        }\n"
    "        if(brk||isEnd){\n"
    "          var se=k-1;\n"
    "          if(se>=segS){\n"
    "            var mi=Math.max(0,Math.min(n-1,from+Math.round((segS+se)/2)));\n"
    "            var col=_biasColor(res.bias[mi],res.pressure[mi]);\n"
    "            var op=Math.min(0.82,lyr.baseOp*(1+res.pressure[mi]*1.80)*opScale);\n"
    "            ctx.fillStyle='rgba('+col.r+','+col.g+','+col.b+','+op.toFixed(3)+')';\n"
    "            ctx.beginPath();\n"
    "            ctx.moveTo(x(from+segS),lyr.top[segS]);\n"
    "            for(var j=segS+1;j<=se;j++)ctx.lineTo(x(from+j),lyr.top[j]);\n"
    "            for(var j=se;j>=segS;j--)ctx.lineTo(x(from+j),lyr.bot[j]);\n"
    "            ctx.closePath();ctx.fill();\n"
    "          }\n"
    "          segS=k;\n"
    "        }\n"
    "      }\n"
    "    }\n"
    "    /* synthetic history watermark */\n"
    "    if(res.synthCount>0&&res.synthCount/res.n>0.05){\n"
    "      var rp2=typeof RP==='function'?RP():68;\n"
    "      ctx.font='600 8px monospace';ctx.textAlign='right';ctx.textBaseline='top';\n"
    "      ctx.fillStyle='rgba(200,170,50,0.48)';\n"
    "      ctx.fillText('\\u007e SYNTHETIC HISTORY',W-rp2-8,4);\n"
    "    }\n"
    "    ctx.restore();\n"
    "  }"
)
html = html.replace(OLD_CLOUD, NEW_CLOUD, 1)

# ── 4. Event labels: compact pill, no subtitle, 40px min spacing ────────────────
OLD_EVENTS = (
    "    if(cfg.showEvents){\n"
    "      ctx.save();ctx.textAlign='center';ctx.textBaseline='middle';\n"
    "      var evSet=new Set();\n"
    "      for(var ei=0;ei<res.events.length;ei++){\n"
    "        var ev=res.events[ei],i=ev.idx;\n"
    "        if(i<AllV.a-1||i>AllV.b+1)continue;\n"
    "        if(evSet.has(i+'_'+ev.type))continue;\n"
    "        evSet.add(i+'_'+ev.type);\n"
    "        var c=cs[i],xx=x(i),isUp=c.c>=c.o;\n"
    "        var yBase=isUp?sc.y(c.h)-18:sc.y(c.l)+18;\n"
    "        var label,r,g,bl;\n"
    "        if(ev.type==='ABSORPTION'){\n"
    "          label='ABSORPTION';r=90;g=60;bl=200;\n"
    "          ctx.font='bold 7px monospace';ctx.fillStyle='rgba('+r+','+g+','+bl+',0.85)';ctx.fillText(label,xx,yBase);\n"
    "          ctx.font='6px monospace';ctx.fillStyle='rgba('+r+','+g+','+bl+',0.55)';ctx.fillText('HIGH VOL · PRICE STALLS',xx,yBase+(isUp?-10:10));\n"
    "        } else if(ev.type==='EXHAUSTION'){\n"
    "          label='EXHAUSTION';r=220;g=130;bl=20;\n"
    "          ctx.font='bold 7px monospace';ctx.fillStyle='rgba('+r+','+g+','+bl+',0.85)';ctx.fillText(label,xx,yBase);\n"
    "          ctx.font='6px monospace';ctx.fillStyle='rgba('+r+','+g+','+bl+',0.55)';ctx.fillText('WEAK FOLLOW-THROUGH',xx,yBase+(isUp?-10:10));\n"
    "        } else if(ev.type==='FLOW_FLIP'){\n"
    "          var b=res.bias[i];\n"
    "          if(b>0){r=0;g=200;bl=220;}else{r=220;g=60;bl=50;}\n"
    "          label='FLOW FLIP';\n"
    "          ctx.font='bold 7px monospace';ctx.fillStyle='rgba('+r+','+g+','+bl+',0.90)';ctx.fillText(label,xx,yBase);\n"
    "          ctx.font='6px monospace';ctx.fillStyle='rgba('+r+','+g+','+bl+',0.55)';ctx.fillText(b>0?'BUYERS IN CONTROL':'SELLERS TAKE OVER',xx,yBase+(isUp?-10:10));\n"
    "          ctx.beginPath();\n"
    "          var ty=isUp?sc.y(c.h)-4:sc.y(c.l)+4,td=isUp?-1:1;\n"
    "          ctx.moveTo(xx-4,ty);ctx.lineTo(xx+4,ty);ctx.lineTo(xx,ty+td*6);ctx.closePath();\n"
    "          ctx.fillStyle='rgba('+r+','+g+','+bl+',0.70)';ctx.fill();\n"
    "        }\n"
    "      }\n"
    "      ctx.restore();\n"
    "    }"
)
assert OLD_EVENTS in html, 'events block anchor not found'
NEW_EVENTS = (
    "    if(cfg.showEvents){\n"
    "      ctx.save();ctx.textAlign='center';ctx.textBaseline='middle';\n"
    "      var evSet=new Set(),lastEvX=-999;\n"
    "      for(var ei=0;ei<res.events.length;ei++){\n"
    "        var ev=res.events[ei],i=ev.idx;\n"
    "        if(i<AllV.a-1||i>AllV.b+1)continue;\n"
    "        if(evSet.has(i+'_'+ev.type))continue;\n"
    "        evSet.add(i+'_'+ev.type);\n"
    "        var c=cs[i],xx=x(i),isUp=c.c>=c.o;\n"
    "        if(Math.abs(xx-lastEvX)<40)continue;\n"
    "        lastEvX=xx;\n"
    "        var yBase=isUp?sc.y(c.h)-9:sc.y(c.l)+9;\n"
    "        var r,g,bl,lbl;\n"
    "        if(ev.type==='ABSORPTION'){lbl='ABS';r=90;g=60;bl=200;}\n"
    "        else if(ev.type==='EXHAUSTION'){lbl='EXH';r=220;g=130;bl=20;}\n"
    "        else{var b=res.bias[i];lbl='FLIP';r=b>0?0:220;g=b>0?200:60;bl=b>0?220:50;}\n"
    "        ctx.font='bold 6px monospace';\n"
    "        var tw=ctx.measureText(lbl).width;\n"
    "        ctx.fillStyle='rgba('+r+','+g+','+bl+',0.12)';\n"
    "        ctx.fillRect(xx-tw/2-4,yBase-6,tw+8,12);\n"
    "        ctx.fillStyle='rgba('+r+','+g+','+bl+',0.70)';\n"
    "        ctx.fillText(lbl,xx,yBase);\n"
    "        if(ev.type==='FLOW_FLIP'){\n"
    "          var ty=isUp?sc.y(c.h)-3:sc.y(c.l)+3,td=isUp?-1:1;\n"
    "          ctx.beginPath();ctx.moveTo(xx-3,ty);ctx.lineTo(xx+3,ty);ctx.lineTo(xx,ty+td*4);\n"
    "          ctx.closePath();ctx.fillStyle='rgba('+r+','+g+','+bl+',0.55)';ctx.fill();\n"
    "        }\n"
    "      }\n"
    "      ctx.restore();\n"
    "    }"
)
html = html.replace(OLD_EVENTS, NEW_EVENTS, 1)

with open('DepthVisionLab-v106_REAL_UI/public/index.html','w',encoding='utf-8') as f:
    f.write(html)

print('patch_150.py applied — Beta 0.150')
print('  CRITICAL FIX: delta condition (buy+sell>0) — historical candles now use synthetic OHLCV')
print('  + drawCloud(): directional (bullish below, bearish above), opacity 0.08→0.28 per layer')
print('  + event labels: compact pill ABS/EXH/FLIP, 6px, no subtitle, 40px min spacing')
print('  + _compute() debug: window._dvlPTDebug=true in console to log data quality')
