#!/usr/bin/env python3
"""patch_197.py — Beta 0.197: Compact order UI + interactive pending line on chart"""
import os
os.chdir(os.path.dirname(os.path.abspath(__file__)))

with open('DepthVisionLab-v106_REAL_UI/public/index.html', 'r', encoding='utf-8') as f:
    html = f.read()

assert html.count('Beta 0.196') >= 10, f'count={html.count("Beta 0.196")}'
html = html.replace('Beta 0.196', 'Beta 0.197')

# ── 1. Replace Trade Bar HTML ─────────────────────────────────────────────────
OLD_TB_HTML = (
    '  <!-- DVL Trade Bar — between TF bar and chart -->\n'
    '  <div id="dvlTradeBar">\n'
    '    <div class="dtb-action-row">\n'
    '      <button class="dtb-btn buy" onclick="window.DVL_PAPER&&DVL_PAPER._submitOrder(\'buy\')">\n'
    '        <svg width="11" height="11" viewBox="0 0 10 10" fill="none" stroke="currentColor" stroke-width="2"><polyline points="5,1 9,5 5,9"/><line x1="1" y1="5" x2="9" y2="5"/></svg>\n'
    '        <span id="dtbBuyLbl">Buy Market</span>\n'
    '      </button>\n'
    '      <button class="dtb-btn sell" onclick="window.DVL_PAPER&&DVL_PAPER._submitOrder(\'sell\')">\n'
    '        <svg width="11" height="11" viewBox="0 0 10 10" fill="none" stroke="currentColor" stroke-width="2"><polyline points="5,9 9,5 5,1"/><line x1="1" y1="5" x2="9" y2="5"/></svg>\n'
    '        <span id="dtbSellLbl">Sell Market</span>\n'
    '      </button>\n'
    '    </div>\n'
    '    <div class="dtb-ctrl-row">\n'
    '      <div class="dtb-cell">\n'
    '        <span class="dtb-lbl">Type</span>\n'
    '        <select class="dtb-sel" id="ppOrderType" onchange="window.DVL_PAPER&&DVL_PAPER._onTypeChange(this.value)">\n'
    '          <option value="market">Market</option>\n'
    '          <option value="limit">Limit</option>\n'
    '          <option value="stop">Stop</option>\n'
    '        </select>\n'
    '      </div>\n'
    '      <div class="dtb-cell">\n'
    '        <span class="dtb-lbl">Size</span>\n'
    '        <input class="dtb-inp" id="ppQty" type="number" min="0" step="0.0001" placeholder="auto">\n'
    '      </div>\n'
    '      <div class="dtb-cell">\n'
    '        <span class="dtb-lbl">Risk %</span>\n'
    '        <input class="dtb-inp" id="ppRiskPct" type="number" min="0.1" max="100" step="0.1" value="1" oninput="window.DVL_PAPER&&DVL_PAPER._updateSummaryBar()">\n'
    '      </div>\n'
    '      <div class="dtb-cell">\n'
    '        <span class="dtb-lbl">RR</span>\n'
    '        <div class="dtb-rr" id="ppRRDisp">—</div>\n'
    '      </div>\n'
    '    </div>\n'
    '    <div class="dtb-limit-row" id="dtbLimitRow">\n'
    '      <span class="dtb-lbl">Price</span>\n'
    '      <input class="dtb-inp" id="ppLimitPx" type="number" step="0.01" placeholder="limit price">\n'
    '    </div>\n'
    '  </div>'
)
assert OLD_TB_HTML in html, 'trade bar HTML not found'

NEW_TB_HTML = (
    '  <!-- DVL Trade Bar — between TF bar and chart -->\n'
    '  <div id="dvlTradeBar">\n'
    '    <div class="dtb-action-row">\n'
    '      <div class="dtb-dd-wrap">\n'
    '        <button class="dtb-btn buy" id="dtbBuyBtn" onclick="window.DVL_PAPER&&DVL_PAPER._openDropdown(\'buy\')">\n'
    '          <span id="dtbBuyLbl">Buy Market</span>\n'
    '          <svg class="dtb-chev" width="8" height="8" viewBox="0 0 10 10" fill="none" stroke="currentColor" stroke-width="2.5"><polyline points="2,3 5,7 8,3"/></svg>\n'
    '        </button>\n'
    '        <div class="dtb-dropdown" id="dtbBuyMenu">\n'
    '          <button class="dtb-di buy" onclick="window.DVL_PAPER&&DVL_PAPER._selectType(\'buy\',\'market\')">Buy Market</button>\n'
    '          <button class="dtb-di buy" onclick="window.DVL_PAPER&&DVL_PAPER._selectType(\'buy\',\'limit\')">Buy Limit</button>\n'
    '          <button class="dtb-di buy" onclick="window.DVL_PAPER&&DVL_PAPER._selectType(\'buy\',\'stop\')">Buy Stop</button>\n'
    '        </div>\n'
    '      </div>\n'
    '      <div class="dtb-dd-wrap">\n'
    '        <button class="dtb-btn sell" id="dtbSellBtn" onclick="window.DVL_PAPER&&DVL_PAPER._openDropdown(\'sell\')">\n'
    '          <span id="dtbSellLbl">Sell Market</span>\n'
    '          <svg class="dtb-chev" width="8" height="8" viewBox="0 0 10 10" fill="none" stroke="currentColor" stroke-width="2.5"><polyline points="2,3 5,7 8,3"/></svg>\n'
    '        </button>\n'
    '        <div class="dtb-dropdown" id="dtbSellMenu">\n'
    '          <button class="dtb-di sell" onclick="window.DVL_PAPER&&DVL_PAPER._selectType(\'sell\',\'market\')">Sell Market</button>\n'
    '          <button class="dtb-di sell" onclick="window.DVL_PAPER&&DVL_PAPER._selectType(\'sell\',\'limit\')">Sell Limit</button>\n'
    '          <button class="dtb-di sell" onclick="window.DVL_PAPER&&DVL_PAPER._selectType(\'sell\',\'stop\')">Sell Stop</button>\n'
    '        </div>\n'
    '      </div>\n'
    '    </div>\n'
    '    <div class="dtb-ctrl-row">\n'
    '      <div class="dtb-cell">\n'
    '        <span class="dtb-lbl">Size</span>\n'
    '        <input class="dtb-inp" id="ppQty" type="number" min="0" step="0.0001" placeholder="auto">\n'
    '      </div>\n'
    '      <div class="dtb-cell">\n'
    '        <span class="dtb-lbl">Risk %</span>\n'
    '        <input class="dtb-inp" id="ppRiskPct" type="number" min="0.1" max="100" step="0.1" value="1" oninput="window.DVL_PAPER&&DVL_PAPER._updateSummaryBar()">\n'
    '      </div>\n'
    '      <div class="dtb-cell">\n'
    '        <span class="dtb-lbl">RR</span>\n'
    '        <div class="dtb-rr" id="ppRRDisp">—</div>\n'
    '      </div>\n'
    '    </div>\n'
    '    <input type="hidden" id="ppOrderType" value="market">\n'
    '    <input type="hidden" id="ppLimitPx" value="">\n'
    '  </div>'
)
html = html.replace(OLD_TB_HTML, NEW_TB_HTML, 1)

# ── 2. Replace Trade Bar CSS (and disable Summary Strip) ──────────────────────
OLD_CSS = (
    '/* ── DVL Trade Bar ── */\n'
    '#dvlTradeBar{display:none;flex-direction:column;gap:5px;padding:6px 8px 5px;background:#020508;border-bottom:1px solid rgba(255,255,255,.06);font-family:monospace;flex-shrink:0;width:100%;box-sizing:border-box;}\n'
    '#dvlTradeBar.dtb-on{display:flex;}\n'
    '.dtb-action-row{display:grid;grid-template-columns:1fr 1fr;gap:7px;}\n'
    '.dtb-btn{height:44px;font-family:monospace;font-size:13px;font-weight:800;border-radius:5px;cursor:pointer;border:1.5px solid;letter-spacing:.08em;transition:all .15s;display:flex;align-items:center;justify-content:center;gap:7px;background:none;}\n'
    '.dtb-btn:active{transform:scale(.97);}\n'
    '.dtb-btn.buy{background:rgba(0,200,80,.08);color:#00ff7a;border-color:rgba(0,210,80,.50);box-shadow:0 0 18px rgba(0,210,80,.15),inset 0 0 12px rgba(0,200,80,.05);}\n'
    '.dtb-btn.buy:hover{background:rgba(0,200,80,.15);box-shadow:0 0 26px rgba(0,210,80,.28);}\n'
    '.dtb-btn.sell{background:rgba(220,30,40,.08);color:#ff3355;border-color:rgba(220,40,50,.50);box-shadow:0 0 18px rgba(220,40,50,.15),inset 0 0 12px rgba(220,30,40,.05);}\n'
    '.dtb-btn.sell:hover{background:rgba(220,30,40,.15);box-shadow:0 0 26px rgba(220,40,50,.28);}\n'
    '.dtb-ctrl-row{display:grid;grid-template-columns:auto 1fr 1fr auto;gap:6px;align-items:end;}\n'
    '.dtb-cell{display:flex;flex-direction:column;gap:2px;}\n'
    '.dtb-lbl{font-size:7px;color:#3a5068;letter-spacing:.08em;text-transform:uppercase;}\n'
    '.dtb-sel,.dtb-inp{background:#060c16;border:1px solid rgba(255,255,255,.08);color:#b8cce0;border-radius:4px;padding:5px 6px;font-family:monospace;font-size:9.5px;width:100%;box-sizing:border-box;}\n'
    '.dtb-sel:focus,.dtb-inp:focus{outline:none;border-color:rgba(0,212,255,.45);}\n'
    '.dtb-rr{font-size:11px;font-weight:700;color:#00d4ff;text-align:center;padding:4px 0 3px;border:1px solid rgba(0,212,255,.20);border-radius:4px;background:#060c16;min-width:40px;font-family:monospace;}\n'
    '.dtb-limit-row{display:none;align-items:center;gap:6px;margin-top:2px;}\n'
    '.dtb-limit-row .dtb-inp{flex:1;}\n'
    '/* ── DVL Summary Strip (fixed bottom) ── */\n'
    '#dvlSummaryStrip{display:none;position:fixed;bottom:0;left:0;right:0;z-index:192;background:#010306;border-top:1px solid rgba(255,255,255,.07);padding:4px 10px;font-family:monospace;align-items:center;gap:0;}\n'
    '#dvlSummaryStrip.dss-on{display:flex;}\n'
    '.dss-item{display:flex;flex-direction:column;align-items:center;gap:1px;flex:1;min-width:0;border-right:1px solid rgba(255,255,255,.04);padding:0 4px;}\n'
    '.dss-item:last-child{border-right:none;}\n'
    '.dss-k{font-size:6.5px;color:#2d4460;letter-spacing:.06em;text-transform:uppercase;white-space:nowrap;}\n'
    '.dss-v{font-size:8.5px;font-weight:700;color:#6a8faf;font-family:monospace;white-space:nowrap;}\n'
    '.dss-v.pos{color:#00cc66;}.dss-v.neg{color:#ff3355;}.dss-v.hi{color:#00d4ff;}\n'
    '.dss-inp{background:none;border:none;border-bottom:1px solid rgba(255,255,255,.10);color:#b8cce0;font-family:monospace;font-size:8.5px;font-weight:700;text-align:center;width:75px;padding:1px 2px;outline:none;}\n'
    '.dss-inp.sl{color:#ff5566;border-bottom-color:rgba(220,60,80,.35);}\n'
    '.dss-inp.tp{color:#00cc66;border-bottom-color:rgba(0,180,80,.35);}\n'
    '.dss-inp:focus{border-bottom-color:rgba(0,212,255,.5);}'
)
assert OLD_CSS in html, 'trade bar CSS not found'

NEW_CSS = (
    '/* ── DVL Trade Bar ── */\n'
    '#dvlTradeBar{display:none;flex-direction:column;gap:4px;padding:4px 8px;background:#020508;border-bottom:1px solid rgba(255,255,255,.06);font-family:monospace;flex-shrink:0;width:100%;box-sizing:border-box;}\n'
    '#dvlTradeBar.dtb-on{display:flex;}\n'
    '.dtb-action-row{display:grid;grid-template-columns:1fr 1fr;gap:6px;}\n'
    '.dtb-dd-wrap{position:relative;}\n'
    '.dtb-btn{height:28px;font-family:monospace;font-size:11px;font-weight:700;border-radius:4px;cursor:pointer;border:1px solid;letter-spacing:.04em;transition:all .12s;display:flex;align-items:center;justify-content:space-between;padding:0 8px;background:none;width:100%;}\n'
    '.dtb-btn:active{transform:scale(.98);}\n'
    '.dtb-btn.buy{background:rgba(0,200,80,.08);color:#00ff7a;border-color:rgba(0,210,80,.40);}\n'
    '.dtb-btn.buy:hover{background:rgba(0,200,80,.14);}\n'
    '.dtb-btn.sell{background:rgba(220,30,40,.08);color:#ff3355;border-color:rgba(220,40,50,.40);}\n'
    '.dtb-btn.sell:hover{background:rgba(220,30,40,.14);}\n'
    '.dtb-chev{flex-shrink:0;opacity:.55;}\n'
    '.dtb-dropdown{display:none;position:absolute;top:calc(100% + 2px);left:0;right:0;background:#060e1a;border:1px solid rgba(255,255,255,.10);border-radius:4px;z-index:210;overflow:hidden;}\n'
    '.dtb-dropdown.open{display:block;}\n'
    '.dtb-di{display:block;width:100%;background:none;border:none;color:#7a96b0;font-family:monospace;font-size:10px;font-weight:600;padding:6px 9px;cursor:pointer;text-align:left;border-bottom:1px solid rgba(255,255,255,.04);}\n'
    '.dtb-di:last-child{border-bottom:none;}\n'
    '.dtb-di.buy:hover{color:#00ff7a;background:rgba(0,200,80,.06);}\n'
    '.dtb-di.sell:hover{color:#ff3355;background:rgba(220,30,40,.06);}\n'
    '.dtb-ctrl-row{display:grid;grid-template-columns:1fr 1fr auto;gap:6px;align-items:end;}\n'
    '.dtb-cell{display:flex;flex-direction:column;gap:1px;}\n'
    '.dtb-lbl{font-size:7px;color:#3a5068;letter-spacing:.08em;text-transform:uppercase;}\n'
    '.dtb-inp{background:#060c16;border:1px solid rgba(255,255,255,.08);color:#b8cce0;border-radius:4px;padding:3px 5px;font-family:monospace;font-size:9.5px;width:100%;box-sizing:border-box;height:22px;}\n'
    '.dtb-inp:focus{outline:none;border-color:rgba(0,212,255,.45);}\n'
    '.dtb-rr{font-size:10px;font-weight:700;color:#00d4ff;text-align:center;border:1px solid rgba(0,212,255,.20);border-radius:4px;background:#060c16;min-width:36px;font-family:monospace;height:22px;display:flex;align-items:center;justify-content:center;padding:0 4px;}\n'
    '/* ── DVL Summary Strip — hidden in trade-bar mode ── */\n'
    '#dvlSummaryStrip{display:none!important;}\n'
    '.dss-item{display:flex;flex-direction:column;align-items:center;gap:1px;flex:1;min-width:0;border-right:1px solid rgba(255,255,255,.04);padding:0 4px;}\n'
    '.dss-item:last-child{border-right:none;}\n'
    '.dss-k{font-size:6.5px;color:#2d4460;letter-spacing:.06em;text-transform:uppercase;white-space:nowrap;}\n'
    '.dss-v{font-size:8.5px;font-weight:700;color:#6a8faf;font-family:monospace;white-space:nowrap;}\n'
    '.dss-v.pos{color:#00cc66;}.dss-v.neg{color:#ff3355;}.dss-v.hi{color:#00d4ff;}\n'
    '.dss-inp{background:none;border:none;border-bottom:1px solid rgba(255,255,255,.10);color:#b8cce0;font-family:monospace;font-size:8.5px;font-weight:700;text-align:center;width:75px;padding:1px 2px;outline:none;}\n'
    '.dss-inp.sl{color:#ff5566;border-bottom-color:rgba(220,60,80,.35);}\n'
    '.dss-inp.tp{color:#00cc66;border-bottom-color:rgba(0,180,80,.35);}\n'
    '.dss-inp:focus{border-bottom-color:rgba(0,212,255,.5);}'
)
html = html.replace(OLD_CSS, NEW_CSS, 1)

# ── 3. Add _pendingLine state variable ────────────────────────────────────────
OLD_STATE_VARS = 'var _drag=null;\nvar _scRef=null;\nvar _drawCache=[];'
assert OLD_STATE_VARS in html, '_state vars not found'
NEW_STATE_VARS = 'var _drag=null;\nvar _scRef=null;\nvar _drawCache=[];\nvar _pendingLine=null;'
html = html.replace(OLD_STATE_VARS, NEW_STATE_VARS, 1)

# ── 4. Replace drawOverlay (add pending line + pending order TP/SL display) ──
OLD_OVERLAY = (
    '/* ── CANVAS OVERLAY (TV-style) ── */\n'
    'function drawOverlay(ctx,W,H,sc,lastPrice,bwPx){\n'
    '  var sym=_sym();\n'
    '  var positions=ST.positions.filter(function(p){return p.symbol===sym;});\n'
    '  var orders=ST.pendingOrders.filter(function(o){return o.symbol===sym;});\n'
    '  var _lpEl=document.getElementById(\'ppLimitPx\');\n'
    '  var _lpVal=_lpEl?parseFloat(_lpEl.value):NaN;\n'
    '  var _lpActive=!isNaN(_lpVal)&&_lpVal>0&&ST.settings&&ST.settings.orderType!==\'market\';\n'
    '  if(!positions.length&&!orders.length&&!_lpActive)return;\n'
    '  var rp=typeof RP===\'function\'?RP():68;\n'
    '  var xR=W-rp-2;\n'
    '  _drawCache=[];\n'
    '\n'
    '  /* Update scale ref for drag */\n'
    '  if(positions.length){\n'
    '    var _rp0=positions[0].entryPrice;\n'
    '    var _ry0=sc.y(_rp0);\n'
    '    var _rp1=_rp0*1.001;\n'
    '    var _ry1=sc.y(_rp1);\n'
    '    if(_ry1!==_ry0)_scRef={refY:_ry0,refP:_rp0,dpDy:(_rp1-_rp0)/(_ry1-_ry0)};\n'
    '  }\n'
    '\n'
    '  ctx.save();\n'
    '  ctx.font=\'bold 9px monospace\';\n'
    '\n'
    '  positions.forEach(function(pos){\n'
    '    var px=_price(sym)||pos.entryPrice;\n'
    '    var yE=sc.y(pos.entryPrice);\n'
    '    var ySL=pos.stopLoss!=null?sc.y(pos.stopLoss):null;\n'
    '    var yTP=pos.takeProfit!=null?sc.y(pos.takeProfit):null;\n'
    '    var isLong=pos.side===\'long\';\n'
    '    var upnl=pos.unrealizedPnl||_upnl(pos);\n'
    '\n'
    '    /* estimated PNL at TP/SL */\n'
    '    var feeRate=ST.settings.feePct/100;\n'
    '    var estTP=pos.takeProfit!=null?(isLong?(pos.takeProfit-pos.entryPrice)*pos.qty:(pos.entryPrice-pos.takeProfit)*pos.qty)-(pos.takeProfit*pos.qty*feeRate)-(pos.openFee||0):null;\n'
    '    var estSL=pos.stopLoss!=null?(isLong?(pos.stopLoss-pos.entryPrice)*pos.qty:(pos.entryPrice-pos.stopLoss)*pos.qty)-(pos.stopLoss*pos.qty*feeRate)-(pos.openFee||0):null;\n'
    '\n'
    '    /* TP line */\n'
    '    if(yTP!=null&&yTP>=-10&&yTP<=H+10){\n'
    '      ctx.lineWidth=1;ctx.setLineDash([]);\n'
    '      ctx.strokeStyle=\'rgba(0,200,100,.75)\';\n'
    '      ctx.beginPath();ctx.moveTo(0,yTP);ctx.lineTo(xR,yTP);ctx.stroke();\n'
    '      var tpTxt=pos.qty.toFixed(3)+(estTP!=null?\'  \'+_fp(estTP)+\' USDT\':\'  TP\');\n'
    '      _drawLineLabel(ctx,xR,yTP,\'rgba(0,30,20,.85)\',\'rgba(0,200,100,1)\',tpTxt,pos.id,\'tp\',false);\n'
    '    }\n'
    '\n'
    '    /* SL line */\n'
    '    if(ySL!=null&&ySL>=-10&&ySL<=H+10){\n'
    '      ctx.lineWidth=1;ctx.setLineDash([]);\n'
    '      ctx.strokeStyle=\'rgba(220,80,50,.75)\';\n'
    '      ctx.beginPath();ctx.moveTo(0,ySL);ctx.lineTo(xR,ySL);ctx.stroke();\n'
    '      var slTxt=pos.qty.toFixed(3)+(estSL!=null?\'  \'+_fp(estSL)+\' USDT\':\'  SL\');\n'
    '      _drawLineLabel(ctx,xR,ySL,\'rgba(30,10,5,.85)\',\'rgba(220,100,70,1)\',slTxt,pos.id,\'sl\',false);\n'
    '    }\n'
    '\n'
    '    /* Entry line */\n'
    '    if(yE>=-10&&yE<=H+10){\n'
    '      ctx.lineWidth=1.5;ctx.setLineDash([4,3]);\n'
    '      ctx.strokeStyle=\'rgba(80,160,255,.75)\';\n'
    '      ctx.beginPath();ctx.moveTo(0,yE);ctx.lineTo(xR,yE);ctx.stroke();\n'
    '      ctx.setLineDash([]);\n'
    '      var eTxt=(isLong?\'L \':\'S \')+pos.qty.toFixed(3)+\'  \'+_fp(upnl)+\' USDT  \'+_fPct(pos.roe||0);\n'
    '      _drawLineLabel(ctx,xR,yE,\'rgba(5,20,50,.9)\',\'rgba(80,160,255,1)\',eTxt,pos.id,\'entry\',true);\n'
    '    }\n'
    '  });\n'
    '\n'
    '  /* pending orders */\n'
    '  orders.forEach(function(o){\n'
    '    if(!o.price)return;\n'
    '    var yO=sc.y(o.price);if(yO<-10||yO>H+10)return;\n'
    '    var col=o.side===\'buy\'?\'rgba(0,200,100,.5)\':\'rgba(200,60,40,.5)\';\n'
    '    ctx.lineWidth=1;ctx.strokeStyle=col;ctx.setLineDash([2,4]);\n'
    '    ctx.beginPath();ctx.moveTo(0,yO);ctx.lineTo(xR,yO);ctx.stroke();\n'
    '    ctx.setLineDash([]);\n'
    '    ctx.fillStyle=col.replace(\'.5\',\'.85\');ctx.textAlign=\'left\';ctx.textBaseline=\'alphabetic\';\n'
    '    ctx.fillText((o.side===\'buy\'?\'Buy\':\'Sell\')+\' \'+o.type+\' \'+_f(o.price,4),6,yO-3);\n'
    '  });\n'
    '\n'
    '  /* Limit/Stop price preview line */\n'
    '  if(_lpActive){\n'
    '    var yLP=sc.y(_lpVal);\n'
    '    if(yLP>=-10&&yLP<=H+10){\n'
    '      ctx.lineWidth=1;ctx.setLineDash([5,4]);\n'
    '      ctx.strokeStyle=\'rgba(255,200,50,0.65)\';\n'
    '      ctx.beginPath();ctx.moveTo(0,yLP);ctx.lineTo(xR,yLP);ctx.stroke();\n'
    '      ctx.setLineDash([]);\n'
    '      var _ltype=(ST.settings.orderType||\'limit\').toUpperCase();\n'
    '      ctx.font=\'bold 9px monospace\';ctx.textAlign=\'left\';ctx.textBaseline=\'alphabetic\';\n'
    '      ctx.shadowColor=\'rgba(0,0,0,0.9)\';ctx.shadowBlur=4;\n'
    '      ctx.fillStyle=\'rgba(255,210,60,0.9)\';\n'
    '      ctx.fillText(_ltype+\' @ \'+_f(_lpVal,4)+ \' — click Buy/Sell to place\',6,yLP-4);\n'
    '      ctx.shadowBlur=0;ctx.shadowColor=\'transparent\';\n'
    '      /* check marker */\n'
    '      ctx.font=\'bold 11px monospace\';ctx.fillStyle=\'rgba(80,220,120,1)\';\n'
    '      ctx.shadowColor=\'rgba(0,0,0,0.9)\';ctx.shadowBlur=4;\n'
    '      ctx.fillText(\'v\',xR-22,yLP+4);\n'
    '      ctx.shadowBlur=0;ctx.shadowColor=\'transparent\';\n'
    '    }\n'
    '  }\n'
    '\n'
    '  ctx.restore();\n'
    '}'
)
assert OLD_OVERLAY in html, 'drawOverlay not found'

NEW_OVERLAY = (
    '/* ── CANVAS OVERLAY (TV-style) ── */\n'
    'function drawOverlay(ctx,W,H,sc,lastPrice,bwPx){\n'
    '  var sym=_sym();\n'
    '  var positions=ST.positions.filter(function(p){return p.symbol===sym;});\n'
    '  var orders=ST.pendingOrders.filter(function(o){return o.symbol===sym;});\n'
    '  if(!positions.length&&!orders.length&&!_pendingLine)return;\n'
    '  var rp=typeof RP===\'function\'?RP():68;\n'
    '  var xR=W-rp-2;\n'
    '  _drawCache=[];\n'
    '\n'
    '  /* Update scale ref for drag */\n'
    '  if(positions.length){\n'
    '    var _rp0=positions[0].entryPrice;\n'
    '    var _ry0=sc.y(_rp0);\n'
    '    var _rp1=_rp0*1.001;\n'
    '    var _ry1=sc.y(_rp1);\n'
    '    if(_ry1!==_ry0)_scRef={refY:_ry0,refP:_rp0,dpDy:(_rp1-_rp0)/(_ry1-_ry0)};\n'
    '  } else if(_pendingLine){\n'
    '    var _rp0=_pendingLine.price;\n'
    '    var _ry0=sc.y(_rp0);\n'
    '    var _rp1=_rp0*1.001;\n'
    '    var _ry1=sc.y(_rp1);\n'
    '    if(_ry1!==_ry0)_scRef={refY:_ry0,refP:_rp0,dpDy:(_rp1-_rp0)/(_ry1-_ry0)};\n'
    '  }\n'
    '\n'
    '  ctx.save();\n'
    '  ctx.font=\'bold 9px monospace\';\n'
    '\n'
    '  positions.forEach(function(pos){\n'
    '    var px=_price(sym)||pos.entryPrice;\n'
    '    var yE=sc.y(pos.entryPrice);\n'
    '    var ySL=pos.stopLoss!=null?sc.y(pos.stopLoss):null;\n'
    '    var yTP=pos.takeProfit!=null?sc.y(pos.takeProfit):null;\n'
    '    var isLong=pos.side===\'long\';\n'
    '    var upnl=pos.unrealizedPnl||_upnl(pos);\n'
    '\n'
    '    /* estimated PNL at TP/SL */\n'
    '    var feeRate=ST.settings.feePct/100;\n'
    '    var estTP=pos.takeProfit!=null?(isLong?(pos.takeProfit-pos.entryPrice)*pos.qty:(pos.entryPrice-pos.takeProfit)*pos.qty)-(pos.takeProfit*pos.qty*feeRate)-(pos.openFee||0):null;\n'
    '    var estSL=pos.stopLoss!=null?(isLong?(pos.stopLoss-pos.entryPrice)*pos.qty:(pos.entryPrice-pos.stopLoss)*pos.qty)-(pos.stopLoss*pos.qty*feeRate)-(pos.openFee||0):null;\n'
    '\n'
    '    /* TP line */\n'
    '    if(yTP!=null&&yTP>=-10&&yTP<=H+10){\n'
    '      ctx.lineWidth=1;ctx.setLineDash([]);\n'
    '      ctx.strokeStyle=\'rgba(0,200,100,.75)\';\n'
    '      ctx.beginPath();ctx.moveTo(0,yTP);ctx.lineTo(xR,yTP);ctx.stroke();\n'
    '      var tpTxt=pos.qty.toFixed(3)+(estTP!=null?\'  \'+_fp(estTP)+\' USDT\':\'  TP\');\n'
    '      _drawLineLabel(ctx,xR,yTP,\'rgba(0,30,20,.85)\',\'rgba(0,200,100,1)\',tpTxt,pos.id,\'tp\',false);\n'
    '    }\n'
    '\n'
    '    /* SL line */\n'
    '    if(ySL!=null&&ySL>=-10&&ySL<=H+10){\n'
    '      ctx.lineWidth=1;ctx.setLineDash([]);\n'
    '      ctx.strokeStyle=\'rgba(220,80,50,.75)\';\n'
    '      ctx.beginPath();ctx.moveTo(0,ySL);ctx.lineTo(xR,ySL);ctx.stroke();\n'
    '      var slTxt=pos.qty.toFixed(3)+(estSL!=null?\'  \'+_fp(estSL)+\' USDT\':\'  SL\');\n'
    '      _drawLineLabel(ctx,xR,ySL,\'rgba(30,10,5,.85)\',\'rgba(220,100,70,1)\',slTxt,pos.id,\'sl\',false);\n'
    '    }\n'
    '\n'
    '    /* Entry line */\n'
    '    if(yE>=-10&&yE<=H+10){\n'
    '      ctx.lineWidth=1.5;ctx.setLineDash([4,3]);\n'
    '      ctx.strokeStyle=\'rgba(80,160,255,.75)\';\n'
    '      ctx.beginPath();ctx.moveTo(0,yE);ctx.lineTo(xR,yE);ctx.stroke();\n'
    '      ctx.setLineDash([]);\n'
    '      var eTxt=(isLong?\'L \':\'S \')+pos.qty.toFixed(3)+\'  \'+_fp(upnl)+\' USDT  \'+_fPct(pos.roe||0);\n'
    '      _drawLineLabel(ctx,xR,yE,\'rgba(5,20,50,.9)\',\'rgba(80,160,255,1)\',eTxt,pos.id,\'entry\',true);\n'
    '    }\n'
    '  });\n'
    '\n'
    '  /* pending orders — draw entry + TP/SL lines */\n'
    '  orders.forEach(function(o){\n'
    '    if(!o.price)return;\n'
    '    var yO=sc.y(o.price);if(yO<-10||yO>H+10)return;\n'
    '    var col=o.side===\'buy\'?\'rgba(0,200,100,.5)\':\'rgba(200,60,40,.5)\';\n'
    '    ctx.lineWidth=1;ctx.strokeStyle=col;ctx.setLineDash([2,4]);\n'
    '    ctx.beginPath();ctx.moveTo(0,yO);ctx.lineTo(xR,yO);ctx.stroke();\n'
    '    ctx.setLineDash([]);\n'
    '    ctx.fillStyle=col.replace(\'.5\',\'.85\');ctx.textAlign=\'left\';ctx.textBaseline=\'alphabetic\';\n'
    '    ctx.fillText((o.side===\'buy\'?\'Buy\':\'Sell\')+\' \'+o.type+\' \'+_f(o.price,4),6,yO-3);\n'
    '    if(o.tp){var yOTP=sc.y(o.tp);if(yOTP>=-10&&yOTP<=H+10){\n'
    '      ctx.lineWidth=1;ctx.strokeStyle=\'rgba(0,200,100,.35)\';ctx.setLineDash([2,3]);\n'
    '      ctx.beginPath();ctx.moveTo(0,yOTP);ctx.lineTo(xR,yOTP);ctx.stroke();\n'
    '      ctx.setLineDash([]);ctx.fillStyle=\'rgba(0,200,100,.55)\';\n'
    '      ctx.fillText(\'TP \'+_f(o.tp,4),6,yOTP-3);\n'
    '    }}\n'
    '    if(o.sl){var yOSL=sc.y(o.sl);if(yOSL>=-10&&yOSL<=H+10){\n'
    '      ctx.lineWidth=1;ctx.strokeStyle=\'rgba(220,80,50,.35)\';ctx.setLineDash([2,3]);\n'
    '      ctx.beginPath();ctx.moveTo(0,yOSL);ctx.lineTo(xR,yOSL);ctx.stroke();\n'
    '      ctx.setLineDash([]);ctx.fillStyle=\'rgba(220,100,70,.55)\';\n'
    '      ctx.fillText(\'SL \'+_f(o.sl,4),6,yOSL-3);\n'
    '    }}\n'
    '  });\n'
    '\n'
    '  /* Interactive pending line (pre-confirmation drag-to-place) */\n'
    '  if(_pendingLine){\n'
    '    var yPL=sc.y(_pendingLine.price);\n'
    '    if(yPL>=-10&&yPL<=H+10){\n'
    '      var isBuy=_pendingLine.side===\'buy\';\n'
    '      var plCol=isBuy?\'rgba(0,220,100,1)\':\'rgba(230,60,60,1)\';\n'
    '      /* TP/SL ghost lines */\n'
    '      if(_pendingLine.tp!=null){var yPTP=sc.y(_pendingLine.tp);\n'
    '        if(yPTP>=-10&&yPTP<=H+10){\n'
    '          ctx.lineWidth=1;ctx.setLineDash([3,3]);\n'
    '          ctx.strokeStyle=\'rgba(0,200,100,0.30)\';\n'
    '          ctx.beginPath();ctx.moveTo(0,yPTP);ctx.lineTo(xR,yPTP);ctx.stroke();\n'
    '          ctx.setLineDash([]);ctx.font=\'bold 9px monospace\';\n'
    '          ctx.fillStyle=\'rgba(0,200,100,0.50)\';ctx.textAlign=\'left\';ctx.textBaseline=\'alphabetic\';\n'
    '          ctx.shadowColor=\'rgba(0,0,0,0.7)\';ctx.shadowBlur=3;\n'
    '          ctx.fillText(\'TP \'+_f(_pendingLine.tp,4),6,yPTP-3);\n'
    '          ctx.shadowBlur=0;ctx.shadowColor=\'transparent\';\n'
    '      }}\n'
    '      if(_pendingLine.sl!=null){var yPSL=sc.y(_pendingLine.sl);\n'
    '        if(yPSL>=-10&&yPSL<=H+10){\n'
    '          ctx.lineWidth=1;ctx.setLineDash([3,3]);\n'
    '          ctx.strokeStyle=\'rgba(220,80,50,0.30)\';\n'
    '          ctx.beginPath();ctx.moveTo(0,yPSL);ctx.lineTo(xR,yPSL);ctx.stroke();\n'
    '          ctx.setLineDash([]);ctx.font=\'bold 9px monospace\';\n'
    '          ctx.fillStyle=\'rgba(220,100,70,0.50)\';ctx.textAlign=\'left\';ctx.textBaseline=\'alphabetic\';\n'
    '          ctx.shadowColor=\'rgba(0,0,0,0.7)\';ctx.shadowBlur=3;\n'
    '          ctx.fillText(\'SL \'+_f(_pendingLine.sl,4),6,yPSL-3);\n'
    '          ctx.shadowBlur=0;ctx.shadowColor=\'transparent\';\n'
    '      }}\n'
    '      /* Main entry line */\n'
    '      ctx.lineWidth=1.5;ctx.setLineDash([]);\n'
    '      ctx.strokeStyle=plCol;\n'
    '      ctx.beginPath();ctx.moveTo(0,yPL);ctx.lineTo(xR,yPL);ctx.stroke();\n'
    '      /* Label */\n'
    '      var pSide=isBuy?\'Buy\':\'Sell\';\n'
    '      var pType=_pendingLine.type.charAt(0).toUpperCase()+_pendingLine.type.slice(1);\n'
    '      var pLbl=pSide+\' \'+pType+\' \'+_f(_pendingLine.price,4)+\'  ← drag\';\n'
    '      ctx.font=\'bold 9px monospace\';ctx.fillStyle=plCol;\n'
    '      ctx.textAlign=\'left\';ctx.textBaseline=\'alphabetic\';\n'
    '      ctx.shadowColor=\'rgba(0,0,0,0.9)\';ctx.shadowBlur=4;\n'
    '      ctx.fillText(pLbl,6,yPL-4);\n'
    '      ctx.shadowBlur=0;ctx.shadowColor=\'transparent\';\n'
    '      /* ✓ confirm and × cancel buttons */\n'
    '      var bW=26,bH=18;\n'
    '      var confirmX=xR-bW*2-8;\n'
    '      var cancelX=xR-bW-4;\n'
    '      var bY=Math.round(yPL-bH/2);\n'
    '      ctx.textAlign=\'center\';ctx.textBaseline=\'middle\';\n'
    '      ctx.fillStyle=\'rgba(0,160,75,0.90)\';\n'
    '      ctx.beginPath();ctx.rect(confirmX,bY,bW,bH);ctx.fill();\n'
    '      ctx.font=\'bold 13px monospace\';ctx.fillStyle=\'#efffef\';\n'
    '      ctx.shadowColor=\'rgba(0,0,0,0.8)\';ctx.shadowBlur=3;\n'
    '      ctx.fillText(\'✓\',confirmX+bW/2,yPL);\n'
    '      ctx.fillStyle=\'rgba(160,30,30,0.90)\';\n'
    '      ctx.beginPath();ctx.rect(cancelX,bY,bW,bH);ctx.fill();\n'
    '      ctx.fillStyle=\'#ffefef\';\n'
    '      ctx.fillText(\'×\',cancelX+bW/2,yPL);\n'
    '      ctx.shadowBlur=0;ctx.shadowColor=\'transparent\';\n'
    '      _drawCache.push({x:confirmX,y:bY,w:bW,h:bH,posId:\'_pending\',field:\'confirm\',hasClose:false,lineY:yPL});\n'
    '      _drawCache.push({x:cancelX,y:bY,w:bW,h:bH,posId:\'_pending\',field:\'cancel\',hasClose:false,lineY:yPL});\n'
    '      _drawCache.push({x:0,y:yPL-12,w:confirmX-6,h:24,posId:\'_pending\',field:\'entry\',hasClose:false,lineY:yPL});\n'
    '    }\n'
    '  }\n'
    '\n'
    '  ctx.restore();\n'
    '}'
)
html = html.replace(OLD_OVERLAY, NEW_OVERLAY, 1)

# ── 5. Replace _initDrag — add pending line interaction ───────────────────────
OLD_DRAG = (
    '/* ── DRAG TP/SL ── */\n'
    'function _initDrag(canvas){\n'
    '  function _getY(e){\n'
    '    var t=e.touches?e.touches[0]:e;\n'
    '    var r=canvas.getBoundingClientRect();\n'
    '    return t.clientY-r.top;\n'
    '  }\n'
    '  function _getX(e){\n'
    '    var t=e.touches?e.touches[0]:e;\n'
    '    var r=canvas.getBoundingClientRect();\n'
    '    return t.clientX-r.left;\n'
    '  }\n'
    '  function _start(e){\n'
    '    if(!ST.enabled||!_scRef)return;\n'
    '    var cy=_getY(e),cx=_getX(e);\n'
    '    /* check close buttons first */\n'
    '    for(var i=0;i<_drawCache.length;i++){\n'
    '      var b=_drawCache[i];\n'
    '      if(b.hasClose&&cx>=b.x+b.w-18&&cx<=b.x+b.w&&cy>=b.y&&cy<=b.y+b.h){\n'
    '        e.preventDefault();e.stopPropagation();_doClose(b.posId,\'manual\');return;\n'
    '      }\n'
    '    }\n'
    '    /* check drag handles for TP/SL */\n'
    '    for(var j=0;j<_drawCache.length;j++){\n'
    '      var bb=_drawCache[j];\n'
    '      if((bb.field===\'tp\'||bb.field===\'sl\')&&Math.abs(cy-bb.lineY)<=10){\n'
    '        e.preventDefault();e.stopPropagation();\n'
    '        _drag={posId:bb.posId,field:bb.field,startY:cy};\n'
    '        window._dvlPaperDragging=true;\n'
    '        return;\n'
    '      }\n'
    '    }\n'
    '  }\n'
    '  function _move(e){\n'
    '    if(!_drag||!_scRef)return;\n'
    '    e.preventDefault();e.stopPropagation();\n'
    '    var cy=_getY(e);\n'
    '    var newPrice=_scRef.refP+(cy-_scRef.refY)*_scRef.dpDy;\n'
    '    var pos=ST.positions.find(function(p){return p.id===_drag.posId;});\n'
    '    if(!pos)return;\n'
    '    if(_drag.field===\'tp\')pos.takeProfit=newPrice;\n'
    '    else pos.stopLoss=newPrice;\n'
    '    if(window.drawSoon)drawSoon();\n'
    '  }\n'
    '  function _end(){\n'
    '    window._dvlPaperDragging=false;\n'
    '    if(!_drag)return;\n'
    '    _save();_drag=null;\n'
    '  }\n'
    '  canvas.addEventListener(\'mousedown\',_start);\n'
    '  canvas.addEventListener(\'mousemove\',_move);\n'
    '  canvas.addEventListener(\'mouseup\',_end);\n'
    '  canvas.addEventListener(\'touchstart\',_start,{passive:false});\n'
    '  canvas.addEventListener(\'touchmove\',_move,{passive:false});\n'
    '  canvas.addEventListener(\'touchend\',_end);\n'
    '}'
)
assert OLD_DRAG in html, '_initDrag not found'

NEW_DRAG = (
    '/* ── DRAG TP/SL + PENDING LINE ── */\n'
    'function _initDrag(canvas){\n'
    '  function _getY(e){\n'
    '    var t=e.touches?e.touches[0]:e;\n'
    '    var r=canvas.getBoundingClientRect();\n'
    '    return t.clientY-r.top;\n'
    '  }\n'
    '  function _getX(e){\n'
    '    var t=e.touches?e.touches[0]:e;\n'
    '    var r=canvas.getBoundingClientRect();\n'
    '    return t.clientX-r.left;\n'
    '  }\n'
    '  function _start(e){\n'
    '    if(!ST.enabled)return;\n'
    '    var cy=_getY(e),cx=_getX(e);\n'
    '    /* pending line buttons and drag handle */\n'
    '    for(var p=0;p<_drawCache.length;p++){\n'
    '      var pb=_drawCache[p];\n'
    '      if(pb.posId===\'_pending\'&&cx>=pb.x&&cx<=pb.x+pb.w&&cy>=pb.y&&cy<=pb.y+pb.h){\n'
    '        e.preventDefault();e.stopPropagation();\n'
    '        if(pb.field===\'confirm\'){_confirmPending();}\n'
    '        else if(pb.field===\'cancel\'){_cancelPending();}\n'
    '        else if(pb.field===\'entry\'&&_scRef){\n'
    '          _drag={posId:\'_pending\',field:\'entry\',startY:cy};\n'
    '          window._dvlPaperDragging=true;\n'
    '        }\n'
    '        return;\n'
    '      }\n'
    '    }\n'
    '    if(!_scRef)return;\n'
    '    /* check close buttons for open positions */\n'
    '    for(var i=0;i<_drawCache.length;i++){\n'
    '      var b=_drawCache[i];\n'
    '      if(b.posId!==\'_pending\'&&b.hasClose&&cx>=b.x+b.w-18&&cx<=b.x+b.w&&cy>=b.y&&cy<=b.y+b.h){\n'
    '        e.preventDefault();e.stopPropagation();_doClose(b.posId,\'manual\');return;\n'
    '      }\n'
    '    }\n'
    '    /* check drag handles for TP/SL on open positions */\n'
    '    for(var j=0;j<_drawCache.length;j++){\n'
    '      var bb=_drawCache[j];\n'
    '      if(bb.posId!==\'_pending\'&&(bb.field===\'tp\'||bb.field===\'sl\')&&Math.abs(cy-bb.lineY)<=10){\n'
    '        e.preventDefault();e.stopPropagation();\n'
    '        _drag={posId:bb.posId,field:bb.field,startY:cy};\n'
    '        window._dvlPaperDragging=true;\n'
    '        return;\n'
    '      }\n'
    '    }\n'
    '  }\n'
    '  function _move(e){\n'
    '    if(!_drag||!_scRef)return;\n'
    '    e.preventDefault();e.stopPropagation();\n'
    '    var cy=_getY(e);\n'
    '    var newPrice=_scRef.refP+(cy-_scRef.refY)*_scRef.dpDy;\n'
    '    if(_drag.posId===\'_pending\'){\n'
    '      if(_pendingLine){\n'
    '        _pendingLine.price=newPrice;\n'
    '        var auto=_autoSLTP(_pendingLine.side===\'buy\'?\'long\':\'short\',newPrice);\n'
    '        _pendingLine.sl=auto.sl;_pendingLine.tp=auto.tp;\n'
    '        var lpEl=document.getElementById(\'ppLimitPx\');\n'
    '        if(lpEl)lpEl.value=newPrice;\n'
    '        _updateSummaryBar();\n'
    '      }\n'
    '    } else {\n'
    '      var pos=ST.positions.find(function(p){return p.id===_drag.posId;});\n'
    '      if(!pos)return;\n'
    '      if(_drag.field===\'tp\')pos.takeProfit=newPrice;\n'
    '      else pos.stopLoss=newPrice;\n'
    '    }\n'
    '    if(window.drawSoon)drawSoon();\n'
    '  }\n'
    '  function _end(){\n'
    '    window._dvlPaperDragging=false;\n'
    '    if(!_drag)return;\n'
    '    _save();_drag=null;\n'
    '  }\n'
    '  canvas.addEventListener(\'mousedown\',_start);\n'
    '  canvas.addEventListener(\'mousemove\',_move);\n'
    '  canvas.addEventListener(\'mouseup\',_end);\n'
    '  canvas.addEventListener(\'touchstart\',_start,{passive:false});\n'
    '  canvas.addEventListener(\'touchmove\',_move,{passive:false});\n'
    '  canvas.addEventListener(\'touchend\',_end);\n'
    '}'
)
html = html.replace(OLD_DRAG, NEW_DRAG, 1)

# ── 6. Replace _submitOrder (keep for market, called from _selectType) ────────
OLD_SUBMIT = (
    'function _submitOrder(side){\n'
    '  _saveSettings();\n'
    '  var set=ST.settings;\n'
    '  var type=set.orderType||\'market\';\n'
    '  var qty=_getNum(\'ppQty\',0);if(qty<=0)qty=null;\n'
    '  var limitPx=_getNum(\'ppLimitPx\',0);if(limitPx<=0)limitPx=null;\n'
    '  var sl=_getNum(\'ppSL\',0);if(sl<=0)sl=null;\n'
    '  var tp=_getNum(\'ppTP\',0);if(tp<=0)tp=null;\n'
    '  placeOrder({side:side,type:type,qty:qty,price:limitPx,triggerPrice:limitPx,sl:sl,tp:tp});\n'
    '}'
)
assert OLD_SUBMIT in html, '_submitOrder not found'
NEW_SUBMIT = (
    'function _submitOrder(side){\n'
    '  _saveSettings();\n'
    '  var qty=_getNum(\'ppQty\',0);if(qty<=0)qty=null;\n'
    '  placeOrder({side:side,type:\'market\',qty:qty});\n'
    '}'
)
html = html.replace(OLD_SUBMIT, NEW_SUBMIT, 1)

# ── 7. Replace _onTypeChange (keep for compat, no longer opens line) ──────────
OLD_TYPE_CHANGE = (
    'function _onTypeChange(type){\n'
    '  ST.settings.orderType=type;\n'
    '  var lbl=type.charAt(0).toUpperCase()+type.slice(1);\n'
    '  var buyLbl=document.getElementById(\'dtbBuyLbl\');\n'
    '  var sellLbl=document.getElementById(\'dtbSellLbl\');\n'
    '  if(buyLbl)buyLbl.textContent=\'Buy \'+lbl;\n'
    '  if(sellLbl)sellLbl.textContent=\'Sell \'+lbl;\n'
    '  var limRow=document.getElementById(\'dtbLimitRow\');\n'
    '  if(limRow)limRow.style.display=(type===\'market\'?\'none\':\'flex\');\n'
    '  _save();\n'
    '}'
)
assert OLD_TYPE_CHANGE in html, '_onTypeChange not found'
NEW_TYPE_CHANGE = (
    'function _onTypeChange(type){\n'
    '  ST.settings.orderType=type;\n'
    '  var otEl=document.getElementById(\'ppOrderType\');\n'
    '  if(otEl)otEl.value=type;\n'
    '  _save();\n'
    '}'
)
html = html.replace(OLD_TYPE_CHANGE, NEW_TYPE_CHANGE, 1)

# ── 8. Replace _updateQuickVis — never show summary strip ─────────────────────
OLD_QV = (
    'function _updateQuickVis(){\n'
    '  var enabled=ST.enabled;\n'
    '  var tb=document.getElementById(\'dvlTradeBar\');\n'
    '  var ss=document.getElementById(\'dvlSummaryStrip\');\n'
    '  if(tb){\n'
    '    if(enabled&&ST.quickVisible)tb.classList.add(\'dtb-on\');\n'
    '    else tb.classList.remove(\'dtb-on\');\n'
    '  }\n'
    '  if(ss){\n'
    '    if(enabled&&ST.quickVisible)ss.classList.add(\'dss-on\');\n'
    '    else ss.classList.remove(\'dss-on\');\n'
    '  }\n'
    '  var qb=document.getElementById(\'ppQuickBtns\');\n'
    '  if(qb)qb.style.display=\'none\';\n'
    '}'
)
assert OLD_QV in html, '_updateQuickVis not found'
NEW_QV = (
    'function _updateQuickVis(){\n'
    '  var enabled=ST.enabled;\n'
    '  var tb=document.getElementById(\'dvlTradeBar\');\n'
    '  if(tb){\n'
    '    if(enabled&&ST.quickVisible)tb.classList.add(\'dtb-on\');\n'
    '    else tb.classList.remove(\'dtb-on\');\n'
    '  }\n'
    '  var qb=document.getElementById(\'ppQuickBtns\');\n'
    '  if(qb)qb.style.display=\'none\';\n'
    '}'
)
html = html.replace(OLD_QV, NEW_QV, 1)

# ── 9. Replace _updateSummaryBar — add pending line RR support ────────────────
OLD_SB = (
    'function _updateSummaryBar(){\n'
    '  var px=_price(_sym())||0;\n'
    '  var slEl=document.getElementById(\'ppSL\');\n'
    '  var tpEl=document.getElementById(\'ppTP\');\n'
    '  var riskEl=document.getElementById(\'ppRiskPct\');\n'
    '  var sl=slEl?parseFloat(slEl.value):NaN;\n'
    '  var tp=tpEl?parseFloat(tpEl.value):NaN;\n'
    '  var riskPct=riskEl?parseFloat(riskEl.value):ST.settings.riskPct;\n'
    '  var eq=_equity();\n'
    '  var riskAmt=isNaN(riskPct)?0:eq*riskPct/100;\n'
    '  var rrStr=\'—\',profitAmt=NaN;\n'
    '  if(!isNaN(sl)&&!isNaN(tp)&&px){\n'
    '    var risk=Math.abs(px-sl),reward=Math.abs(tp-px);\n'
    '    if(risk>0){rrStr=\'1:\'+(reward/risk).toFixed(1);profitAmt=riskAmt*(reward/risk);}\n'
    '  }\n'
    '  var rrDisp=document.getElementById(\'ppRRDisp\');\n'
    '  if(rrDisp)rrDisp.textContent=rrStr;\n'
    '  var dEntry=document.getElementById(\'dssEntry\');\n'
    '  if(dEntry)dEntry.textContent=px?_f(px,2):\'—\';\n'
    '  var dRisk=document.getElementById(\'dssRisk\');\n'
    '  if(dRisk)dRisk.textContent=isNaN(riskPct)?\'—\':riskPct.toFixed(1)+\'%\';\n'
    '  var dProfit=document.getElementById(\'dssProfit\');\n'
    '  if(dProfit){\n'
    '    dProfit.textContent=!isNaN(profitAmt)?\'%s\'+_f(profitAmt):\'—\';\n'  # placeholder to check
    '    dProfit.className=\'dss-v \'+(profitAmt>0?\'pos\':\'\')\n'
    '  }\n'
)
# Build exact old string to find and replace
OLD_SB_EXACT = (
    'function _updateSummaryBar(){\n'
    '  var px=_price(_sym())||0;\n'
    '  var slEl=document.getElementById(\'ppSL\');\n'
    '  var tpEl=document.getElementById(\'ppTP\');\n'
    '  var riskEl=document.getElementById(\'ppRiskPct\');\n'
    '  var sl=slEl?parseFloat(slEl.value):NaN;\n'
    '  var tp=tpEl?parseFloat(tpEl.value):NaN;\n'
    '  var riskPct=riskEl?parseFloat(riskEl.value):ST.settings.riskPct;\n'
    '  var eq=_equity();\n'
    '  var riskAmt=isNaN(riskPct)?0:eq*riskPct/100;\n'
    '  var rrStr=\'—\',profitAmt=NaN;\n'
    '  if(!isNaN(sl)&&!isNaN(tp)&&px){\n'
    '    var risk=Math.abs(px-sl),reward=Math.abs(tp-px);\n'
    '    if(risk>0){rrStr=\'1:\'+(reward/risk).toFixed(1);profitAmt=riskAmt*(reward/risk);}\n'
    '  }\n'
    '  var rrDisp=document.getElementById(\'ppRRDisp\');\n'
    '  if(rrDisp)rrDisp.textContent=rrStr;'
)
assert OLD_SB_EXACT in html, '_updateSummaryBar start not found'
NEW_SB_EXACT = (
    'function _updateSummaryBar(){\n'
    '  var px=_price(_sym())||0;\n'
    '  var slEl=document.getElementById(\'ppSL\');\n'
    '  var tpEl=document.getElementById(\'ppTP\');\n'
    '  var riskEl=document.getElementById(\'ppRiskPct\');\n'
    '  var sl=slEl?parseFloat(slEl.value):NaN;\n'
    '  var tp=tpEl?parseFloat(tpEl.value):NaN;\n'
    '  var riskPct=riskEl?parseFloat(riskEl.value):ST.settings.riskPct;\n'
    '  var eq=_equity();\n'
    '  var riskAmt=isNaN(riskPct)?0:eq*riskPct/100;\n'
    '  var rrStr=\'—\',profitAmt=NaN;\n'
    '  /* Use pending line for RR when in placement mode */\n'
    '  if(_pendingLine&&_pendingLine.sl!=null&&_pendingLine.tp!=null){\n'
    '    var entry=_pendingLine.price;\n'
    '    var risk=Math.abs(entry-_pendingLine.sl),reward=Math.abs(_pendingLine.tp-entry);\n'
    '    if(risk>0){rrStr=\'1:\'+(reward/risk).toFixed(1);profitAmt=riskAmt*(reward/risk);}\n'
    '  } else if(!isNaN(sl)&&!isNaN(tp)&&px){\n'
    '    var risk=Math.abs(px-sl),reward=Math.abs(tp-px);\n'
    '    if(risk>0){rrStr=\'1:\'+(reward/risk).toFixed(1);profitAmt=riskAmt*(reward/risk);}\n'
    '  }\n'
    '  var rrDisp=document.getElementById(\'ppRRDisp\');\n'
    '  if(rrDisp)rrDisp.textContent=rrStr;'
)
html = html.replace(OLD_SB_EXACT, NEW_SB_EXACT, 1)

# ── 10. Replace _initTradeBar — simplified for new dropdown UI ────────────────
OLD_INIT_TB = (
    'function _initTradeBar(){\n'
    '  var set=ST.settings;\n'
    '  var ot=document.getElementById(\'ppOrderType\');\n'
    '  if(ot)ot.value=set.orderType||\'market\';\n'
    '  var rp=document.getElementById(\'ppRiskPct\');\n'
    '  if(rp)rp.value=set.riskPct||1;\n'
    '  var type=set.orderType||\'market\';\n'
    '  var lbl=type.charAt(0).toUpperCase()+type.slice(1);\n'
    '  var buyLbl=document.getElementById(\'dtbBuyLbl\');\n'
    '  var sellLbl=document.getElementById(\'dtbSellLbl\');\n'
    '  if(buyLbl)buyLbl.textContent=\'Buy \'+lbl;\n'
    '  if(sellLbl)sellLbl.textContent=\'Sell \'+lbl;\n'
    '  var limRow=document.getElementById(\'dtbLimitRow\');\n'
    '  if(limRow)limRow.style.display=(type===\'market\'?\'none\':\'flex\');\n'
    '}'
)
assert OLD_INIT_TB in html, '_initTradeBar not found'
NEW_INIT_TB = (
    'function _initTradeBar(){\n'
    '  var set=ST.settings;\n'
    '  var rp=document.getElementById(\'ppRiskPct\');\n'
    '  if(rp)rp.value=set.riskPct||1;\n'
    '  var otEl=document.getElementById(\'ppOrderType\');\n'
    '  if(otEl)otEl.value=set.orderType||\'market\';\n'
    '}'
)
html = html.replace(OLD_INIT_TB, NEW_INIT_TB, 1)

# ── 11. Add dropdown + pending line functions before _checkTPSL ───────────────
OLD_CHECK = 'function _checkTPSL(){'
assert OLD_CHECK in html, '_checkTPSL not found'
NEW_FUNCS_PLUS_CHECK = (
    'function _openDropdown(side){\n'
    '  var buyM=document.getElementById(\'dtbBuyMenu\');\n'
    '  var sellM=document.getElementById(\'dtbSellMenu\');\n'
    '  if(side===\'buy\'){\n'
    '    if(buyM)buyM.classList.toggle(\'open\');\n'
    '    if(sellM)sellM.classList.remove(\'open\');\n'
    '  } else {\n'
    '    if(sellM)sellM.classList.toggle(\'open\');\n'
    '    if(buyM)buyM.classList.remove(\'open\');\n'
    '  }\n'
    '}\n'
    'function _closeDropdowns(){\n'
    '  var buyM=document.getElementById(\'dtbBuyMenu\');\n'
    '  var sellM=document.getElementById(\'dtbSellMenu\');\n'
    '  if(buyM)buyM.classList.remove(\'open\');\n'
    '  if(sellM)sellM.classList.remove(\'open\');\n'
    '}\n'
    'function _selectType(side,type){\n'
    '  _closeDropdowns();\n'
    '  ST.settings.orderType=type;\n'
    '  var capType=type.charAt(0).toUpperCase()+type.slice(1);\n'
    '  var lbl=document.getElementById(side===\'buy\'?\'dtbBuyLbl\':\'dtbSellLbl\');\n'
    '  if(lbl)lbl.textContent=(side===\'buy\'?\'Buy \':\'Sell \')+capType;\n'
    '  var otEl=document.getElementById(\'ppOrderType\');\n'
    '  if(otEl)otEl.value=type;\n'
    '  if(type===\'market\'){\n'
    '    _submitOrder(side);\n'
    '  } else {\n'
    '    _startPending(side,type);\n'
    '  }\n'
    '  _save();\n'
    '}\n'
    'function _startPending(side,type){\n'
    '  var px=_price(_sym());\n'
    '  if(!px||isNaN(px))return;\n'
    '  var auto=_autoSLTP(side===\'buy\'?\'long\':\'short\',px);\n'
    '  _pendingLine={side:side,type:type,price:px,sl:auto.sl,tp:auto.tp};\n'
    '  var lpEl=document.getElementById(\'ppLimitPx\');\n'
    '  if(lpEl)lpEl.value=px;\n'
    '  _updateSummaryBar();\n'
    '  _notif((side===\'buy\'?\'Buy\':\'Sell\')+\' \'+type+\' — drag line to set price, then ✓\');\n'
    '  if(window.drawSoon)drawSoon();\n'
    '}\n'
    'function _confirmPending(){\n'
    '  if(!_pendingLine)return;\n'
    '  var p=_pendingLine;\n'
    '  _pendingLine=null;\n'
    '  var auto=_autoSLTP(p.side===\'buy\'?\'long\':\'short\',p.price);\n'
    '  placeOrder({side:p.side,type:p.type,price:p.price,triggerPrice:p.price,sl:p.sl!=null?p.sl:auto.sl,tp:p.tp!=null?p.tp:auto.tp});\n'
    '  var lpEl=document.getElementById(\'ppLimitPx\');\n'
    '  if(lpEl)lpEl.value=\'\';\n'
    '  _updateSummaryBar();\n'
    '  if(window.drawSoon)drawSoon();\n'
    '}\n'
    'function _cancelPending(){\n'
    '  _pendingLine=null;\n'
    '  var lpEl=document.getElementById(\'ppLimitPx\');\n'
    '  if(lpEl)lpEl.value=\'\';\n'
    '  _updateSummaryBar();\n'
    '  if(window.drawSoon)drawSoon();\n'
    '}\n'
    'function _checkTPSL(){'
)
html = html.replace(OLD_CHECK, NEW_FUNCS_PLUS_CHECK, 1)

# ── 12. Update init() — add dropdown outside-click + version bump ─────────────
OLD_INIT = (
    'function init(){\n'
    '  _load();\n'
    '  _initTradeBar();\n'
    '  _updateQuickVis();\n'
    '  var cv=document.getElementById(\'mainCanvas\')||document.querySelector(\'#chartWrap canvas\')||document.querySelector(\'canvas\');\n'
    '  if(cv)_initDrag(cv);\n'
    '  _initOutsideClick();\n'
    '  if(ST.enabled){\n'
    '    var badge=document.getElementById(\'paperTradingBadge\');\n'
    '    if(badge)badge.style.display=\'block\';\n'
    '  }\n'
    '  setInterval(_pollOtherSymbols,3000);\n'
    '  setInterval(_checkTPSL,1000);\n'
    '  console.log(\'[DVL Paper] v0.196 ready — balance:\',ST.account.balance,ST.account.currency);\n'
    '}'
)
assert OLD_INIT in html, 'init() not found'
NEW_INIT = (
    'function init(){\n'
    '  _load();\n'
    '  _initTradeBar();\n'
    '  _updateQuickVis();\n'
    '  var cv=document.getElementById(\'mainCanvas\')||document.querySelector(\'#chartWrap canvas\')||document.querySelector(\'canvas\');\n'
    '  if(cv)_initDrag(cv);\n'
    '  _initOutsideClick();\n'
    '  document.addEventListener(\'click\',function(e){\n'
    '    var tb=document.getElementById(\'dvlTradeBar\');\n'
    '    if(tb&&!tb.contains(e.target))_closeDropdowns();\n'
    '  },true);\n'
    '  if(ST.enabled){\n'
    '    var badge=document.getElementById(\'paperTradingBadge\');\n'
    '    if(badge)badge.style.display=\'block\';\n'
    '  }\n'
    '  setInterval(_pollOtherSymbols,3000);\n'
    '  setInterval(_checkTPSL,1000);\n'
    '  console.log(\'[DVL Paper] v0.197 ready — balance:\',ST.account.balance,ST.account.currency);\n'
    '}'
)
html = html.replace(OLD_INIT, NEW_INIT, 1)

# ── 13. Update exports — add new public functions ─────────────────────────────
OLD_EXPORTS = (
    '  _updateStopsFromUI:_updateStopsFromUI,_toggleQuick:_toggleQuick,_onTypeChange:_onTypeChange,_updateSummaryBar:_updateSummaryBar,_toggleAdv:_toggleAdv,_initTradeBar:_initTradeBar\n'
    '};'
)
assert OLD_EXPORTS in html, 'exports not found'
NEW_EXPORTS = (
    '  _updateStopsFromUI:_updateStopsFromUI,_toggleQuick:_toggleQuick,_onTypeChange:_onTypeChange,_updateSummaryBar:_updateSummaryBar,_toggleAdv:_toggleAdv,_initTradeBar:_initTradeBar,\n'
    '  _openDropdown:_openDropdown,_selectType:_selectType,_startPending:_startPending,_confirmPending:_confirmPending,_cancelPending:_cancelPending\n'
    '};'
)
html = html.replace(OLD_EXPORTS, NEW_EXPORTS, 1)

with open('DepthVisionLab-v106_REAL_UI/public/index.html', 'w', encoding='utf-8') as f:
    f.write(html)

print('patch_197.py applied — Beta 0.197')
print('  + Compact Buy/Sell dropdown buttons (28px height vs 44px)')
print('  + dvlSummaryStrip permanently hidden (display:none!important)')
print('  + Interactive pending line on chart for Limit/Stop orders')
print('  + Drag pending line to set price, auto TP/SL at 1:1 preview')
print('  + Confirm (✓) places order with auto TP/SL, Cancel (×) removes line')
print('  + Dragging trade lines disables chart pan (existing behavior)')
print('  + Pending order TP/SL lines shown on chart after confirmation')
